### ISSUE TITLE
Mix tailwind and basic style

### ISSUE THREAD

**Issue by MartinRdw** [vadimdemedes/tailwind-rn#10]
Hi, thanks for this great package, it is possible to mix tailwind and basic style like that ?

```
style={
    (tailwind("bg-gray-800 flex-row items-center py-6")),
    { backgroundColor: global.currentScreenIndex === key ? textCurrent : textNotCurrent }
}
```

**Comment by inspire22** [comment]
I think you want the ES6 expansion operator, so it should be something like style={...tailwind('blah'), backgroundColor: '#fff'}

**Comment by vadimdemedes** [comment]
@inspire22 is right.

```js
style={{...tailwind('text-blue-500'), backgroundColor: '#000'}}
```

**Comment by MartinRdw** [comment]
Thanks @inspire22!
