### ISSUE TITLE
[Missing documentation] How to use `tailwind-rn` with the TailwindCSS intellisense plugin

### ISSUE THREAD

**Issue by ianwijma** [vadimdemedes/tailwind-rn#100]
Hey,

Loving being able to use TailwindCSS in react native. But using TailwindCSS without intellisense is do-able, but without indepth knowledge of TailwindCSS and the projects settings is a pain. 

After some digging I found that the [Tailwind CSS IntelliSense](https://marketplace.visualstudio.com/items?itemName=bradlc.vscode-tailwindcss) can support `tailwind-rn` with some setting editing.

The following [comment](tailwindlabs/tailwindcss#7553) basically explains how to add it and thought it might be great to add this to the project's README.

**Comment by ifuncoding** [comment]
i used:
`"tailwindCSS.experimental.classRegex": ["tailwind\\('([^)]*)\\')", "'([^']*)'"]`
But it still not working with .tsx

**Comment by ianwijma** [comment]
> i used: `"tailwindCSS.experimental.classRegex": ["tailwind\\('([^)]*)\\')", "'([^']*)'"]` But it still not working with .tsx

Yeah indeed, I've something quite similar, but a small edit. Just created this issue so I can create a PR against it.

**Comment by buitrbao222** [comment]
> i used: `"tailwindCSS.experimental.classRegex": ["tailwind\\('([^)]*)\\')", "'([^']*)'"]` But it still not working with .tsx

This worked for me. Thanks!

**Comment by enchorb** [comment]
Anyone know how to get this working for JetBrains IDEs (IDEA/WebStorm), their Tailwind plugin seem to be quite neglected

**Comment by kneza23** [comment]
i just added "style" to class attributes in plugin preferences

**Comment by byStrange** [comment]
yoooo, it worked for me thank you , I've tried billions of regex in settings.json none of'em worked

**Comment by ianwijma** [comment]
Closing the PR, there seem to be a big in the comments.
