### ISSUE TITLE
Support dark mode

### ISSUE THREAD

**Issue by sanyam-yojak** [vadimdemedes/tailwind-rn#107]
i cant able to detect how i can implement dark mode can any one help me

**Comment by vadimdemedes** [comment]
It's not supported yet. It will be supported in the next major release.

**Comment by vadimdemedes** [comment]
Just released [v4.0.0](https://github.com/vadimdemedes/tailwind-rn/releases/tag/v4.0.0) with support for dark mode!

**Comment by monkeybobby** [comment]
in simulator , the dark is be invalid , this is a  expo go bug ?
