### ISSUE TITLE
Is there a way to change the output of the styles.json?

### ISSUE THREAD

**Issue by johhansantana** [vadimdemedes/tailwind-rn#108]
I would like to move it inside a specific folder instead of having it in the root folder.

**Comment by vadimdemedes** [comment]
The new `tailwind-rn` CLI in the latest [v4.0.0](https://github.com/vadimdemedes/tailwind-rn/releases/tag/v4.0.0) release has a `--output` flag, which you can use to customize where the output JSON is written.
