### ISSUE TITLE
Support Tailwind v3.x

### ISSUE THREAD

**Issue by pvinis** [vadimdemedes/tailwind-rn#116]
what is needed for that?

**Comment by MaganAnkur** [comment]
@pvinis npx create-tailwind-rn not generating CSS with tailwind v3

**Comment by vadimdemedes** [comment]
I'm currently working on a major new release to support latest Tailwind in `v4` branch.

**Comment by vadimdemedes** [comment]
Duplicate of https://github.com/vadimdemedes/tailwind-rn/issues/71.
