### ISSUE TITLE
Styles are generated but not applied (version 4.0.0)

### ISSUE THREAD

**Issue by MicroDroid** [vadimdemedes/tailwind-rn#122]
Hello, I am using version 4.0.0 of this package in a new project as such:

![image](https://user-images.githubusercontent.com/8523135/148834587-a902a1cf-9436-4ce4-9b78-cab8193cf3db.png)

(My `tailwind.config.js` does have the `error` color).

The styles are generated in `tailwind.css` and then in `tailwind.json` but eventually the styles are not really applied.

**UPDATE:** The styles in `tailwind.json` disappeared after restarting the entire stack of processes.
**UPDATE 2:** Deleted both files and restarted watcher and now both are left empty.
**UPDATE 3:** Saving the component file a lot of times eventually caused the JSON file to be generated, but the styles are still not applied (at least per the last refresh). *I very much think the files are generated / not generated just pretty randomly*.

**Comment by vadimdemedes** [comment]
You need to put `TailwindProvider` above `App` component, otherwise `useTailwind` hook doesn't have access to Tailwind utilities. Like this:

```jsx
import {SafeAreaView, View, Text} from 'react-native';
import {TailwindProvider, useTailwind} from 'tailwind-rn';
import utilities from './tailwind.json';

const App = () => {
	const tailwind = useTailwind();

	return (
		<SafeAreaView style={tailwind('h-full')}>
			<View style={tailwind('pt-12 items-center')}>
				<View style={tailwind('bg-blue-200 px-3 py-1 rounded-full')}>
					<Text style={tailwind('text-blue-800 font-semibold')}>
						Hello Tailwind
					</Text>
				</View>
			</View>
		</SafeAreaView>
	);
};

const Root = () => (
	<TailwindProvider utilities={utilities}>
		<App />
	</TailwindProvider>
);

export default Root;
```

**Comment by MicroDroid** [comment]
This worked, thanks.

**Comment by vadimdemedes** [comment]
Also, make sure to configure `content` in `tailwind.config.js` for JIT compiler to work properly. See https://tailwindcss.com/docs/content-configuration.
