### ISSUE TITLE
Unsupported Tailwind class

### ISSUE THREAD

**Issue by jamesvsshark** [vadimdemedes/tailwind-rn#124]
Hello,

I started a new expo project and had your version 3 package working. After updating to version 4 -- it appears all classes are missing.

Maybe this is something silly on my end but I have spent some time trying to figure it out but unable to.

Any idea what I could be doing wrong?

Thank you,

Unsupported Tailwind class: "flex"
at node_modules/tailwind-rn/dist/create.js:35:16 in tailwind
at components/Header.js:10:25 in Header

Unsupported Tailwind class: "flex-row"
at node_modules/tailwind-rn/dist/create.js:35:16 in tailwind
at components/Header.js:10:25 in Header

Unsupported Tailwind class: "px-4"
at node_modules/tailwind-rn/dist/create.js:35:16 in tailwind
at components/Header.js:10:25 in Header

Unsupported Tailwind class: "items-center"
at node_modules/tailwind-rn/dist/create.js:35:16 in tailwind
at components/Header.js:10:25 in Header

Unsupported Tailwind class: "justify-between"
at node_modules/tailwind-rn/dist/create.js:35:16 in tailwind
at components/Header.js:10:25 in Header

Unsupported Tailwind class: "mx-2"
at node_modules/tailwind-rn/dist/create.js:35:16 in tailwind
at components/Header.js:24:27 in Header

Unsupported Tailwind class: "flex"
at node_modules/tailwind-rn/dist/create.js:35:16 in tailwind
at components/Header.js:21:27 in Header

Unsupported Tailwind class: "flex-row"
at node_modules/tailwind-rn/dist/create.js:35:16 in tailwind
at components/Header.js:21:27 in Header

Unsupported Tailwind class: "text-gray-300"
at node_modules/tailwind-rn/dist/create.js:35:16 in tailwind
at components/Header.js:24:27 in Header

Unsupported Tailwind class: "mx-2"
at node_modules/tailwind-rn/dist/create.js:35:16 in tailwind
at components/Header.js:30:35 in Header

Unsupported Tailwind class: "px-4"
at node_modules/tailwind-rn/dist/create.js:35:16 in tailwind
at pages/Requests.js:9:4 in Requests

Unsupported Tailwind class: "flex"
at node_modules/tailwind-rn/dist/create.js:35:16 in tailwind
at pages/Requests.js:9:4 in Requests

Unsupported Tailwind class: "py-4"
at node_modules/tailwind-rn/dist/create.js:35:16 in tailwind
at pages/Requests.js:9:4 in Requests

Unsupported Tailwind class: "flex"
at node_modules/tailwind-rn/dist/create.js:35:16 in tailwind
at pages/Requests.js:10:6 in Requests

Unsupported Tailwind class: "flex-row"
at node_modules/tailwind-rn/dist/create.js:35:16 in tailwind
at pages/Requests.js:10:6 in Requests

Unsupported Tailwind class: "justify-between"
at node_modules/tailwind-rn/dist/create.js:35:16 in tailwind
at pages/Requests.js:10:6 in Requests

Unsupported Tailwind class: "items-center"
at node_modules/tailwind-rn/dist/create.js:35:16 in tailwind
at pages/Requests.js:10:6 in Requests

Unsupported Tailwind class: "font-semibold"
at node_modules/tailwind-rn/dist/create.js:35:16 in tailwind
at pages/Requests.js:11:8 in Requests

Unsupported Tailwind class: "text-lg"
at node_modules/tailwind-rn/dist/create.js:35:16 in tailwind
at pages/Requests.js:11:8 in Requests

Unsupported Tailwind class: "rounded"
at node_modules/tailwind-rn/dist/create.js:35:16 in tailwind
at pages/Requests.js:12:8 in Requests

Unsupported Tailwind class: "border"
at node_modules/tailwind-rn/dist/create.js:35:16 in tailwind
at pages/Requests.js:12:8 in Requests

Unsupported Tailwind class: "border-solid"
at node_modules/tailwind-rn/dist/create.js:35:16 in tailwind
at pages/Requests.js:12:8 in Requests

Unsupported Tailwind class: "border-sky-200"
at node_modules/tailwind-rn/dist/create.js:35:16 in tailwind
at pages/Requests.js:12:8 in Requests

Unsupported Tailwind class: "text-blue-600"
at node_modules/tailwind-rn/dist/create.js:35:16 in tailwind
at pages/Requests.js:15:10 in Requests

Unsupported Tailwind class: "py-1"
at node_modules/tailwind-rn/dist/create.js:35:16 in tailwind
at pages/Requests.js:15:10 in Requests

Unsupported Tailwind class: "px-3"
at node_modules/tailwind-rn/dist/create.js:35:16 in tailwind
at pages/Requests.js:15:10 in Requests

**Comment by jamesvsshark** [comment]
I've debugged it and found that utilities variable here is an empty object.

![image](https://user-images.githubusercontent.com/3740593/149051598-6b884ca5-4c57-4264-83a1-0b3cc1fdca87.png)

**Comment by peteysmallz** [comment]
I'm also experiencing this problem on the upgrade..

**Comment by rezik007** [comment]
I'm a new one here but experienced the same problem.

**Comment by vadimdemedes** [comment]
Have you followed the [migration guide](https://github.com/vadimdemedes/tailwind-rn/blob/master/migrate.md)?

**Comment by camillo18tre** [comment]
Same issue here but the json is generated correctly.
<img width="1030" alt="Schermata 2022-01-13 alle 10 44 13" src="https://user-images.githubusercontent.com/38567269/149305789-2c7d607f-7291-4a0c-9746-fa6f41def75f.png">

**Comment by peteysmallz** [comment]
> Have you followed the [migration guide](https://github.com/vadimdemedes/tailwind-rn/blob/master/migrate.md)? It sounds like some steps were missed, which causes Tailwind to either not generate the CSS or `tailwind-rn` not generate the necessary JSON file to use at runtime.

I have tried to follow the migration guide as best I can. The steps are clear. I would be curious if anyone finds a solution. I've tried to get around it, without success. Love the utility of this library. Excited to use the upgrade!

**Comment by olabodeeto** [comment]
I'm having ssme issue here.

Unsupported Tailwind class: "pt-12"
at node_modules/tailwind-rn/dist/create.js:35:16 in tailwind
at node_modules/react-native/Libraries/Core/setUpReactRefresh.js:43:6 in Refresh.performReactRefresh
at node_modules/metro-runtime/src/polyfills/require.js:655:10 in setTimeout$argument_0

Unsupported Tailwind class: "items-center"
at node_modules/tailwind-rn/dist/create.js:35:16 in tailwind
at node_modules/react-native/Libraries/Core/setUpReactRefresh.js:43:6 in Refresh.performReactRefresh
at node_modules/metro-runtime/src/polyfills/require.js:655:10 in setTimeout$argument_0

› Reloading apps
iOS Bundling complete 48ms
iOS Running app on iPhone 12

Unsupported Tailwind class: "pt-12"
at node_modules/tailwind-rn/dist/create.js:35:16 in tailwind
at app/screens/public/LandingScreen.js:13:27 in LandingScreen
at node_modules/react-native/Libraries/ReactNative/renderApplication.js:58:4 in renderApplication
at node_modules/react-native/Libraries/ReactNative/AppRegistry.js:117:25 in runnables.appKey.run
at node_modules/react-native/Libraries/ReactNative/AppRegistry.js:202:4 in runApplication

Unsupported Tailwind class: "items-center"
at node_modules/tailwind-rn/dist/create.js:35:16 in tailwind
at app/screens/public/LandingScreen.js:13:27 in LandingScreen
at node_modules/react-native/Libraries/ReactNative/renderApplication.js:58:4 in renderApplication
at node_modules/react-native/Libraries/ReactNative/AppRegistry.js:117:25 in runnables.appKey.run
at node_modules/react-native/Libraries/ReactNative/AppRegistry.js:202:4 in runApplication

Unsupported Tailwind class: "pt-12"
at node_modules/tailwind-rn/dist/create.js:35:16 in tailwind
at app/screens/public/LandingScreen.js:13:27 in LandingScreen

Unsupported Tailwind class: "items-center"

**Comment by technical-shoubhik** [comment]
getting same issue - 
Unsupported Tailwind class: "text-xl"

**Comment by technical-shoubhik** [comment]
did you guys find any solution ?

**Comment by jeffersonreis** [comment]
I have the same problem in this version

**Comment by jamesvsshark** [comment]
> did you guys find any solution?

I've been using v3.

Some observations I noticed on v4.

- input.css file only has one directive import
- output tailwind.css file is blank

Are these concerns? Does anyone else have the same observations?

**Comment by ilyapas** [comment]
> > did you guys find any solution?
> 
> I've been using v3.
> 
> Some observations I noticed on v4.
> 
>     * input.css file only has one directive import
> 
>     * output tailwind.css file is blank
> 
> 
> Are these concerns? Does anyone else have the same observations?

yep, I can confirm both. can't get it to work with v4 after following the migration guide

**Comment by ilyapas** [comment]
Ok, I've figured it out: the step if the installation guide where you should configure the **content** field of the _tailwind.config.js_ is not optional. If you leave it empty tailwind.css and tailwind.json end up empty as well. When it's properly configured the build:tailwind / dev:tailwind scripts generate the output files with the styles you are using in the sources and everything works fine.

**Comment by jamesvsshark** [comment]
What did you set the content to be? My source code is at the root of the project.

Thank you.

**Comment by ilyapas** [comment]
I've set mine to `content: ["./screens/**/*.js", "./components/**/*.js"]`

**Comment by peteysmallz** [comment]
That was it - thank you @ilyapas

**Comment by Vann-Dev** [comment]
Do you guys have any solution?, got same error, but the class is already added at `tailwind.json`, `tailwind.css`, also the content have been set
![image](https://user-images.githubusercontent.com/82990248/149683472-6a12e464-8d55-4ea5-b8f2-adc82180efee.png)
![image](https://user-images.githubusercontent.com/82990248/149683488-6aa86e7c-39fc-4ccd-84c2-9315f6a22764.png)

**Comment by olabodeeto** [comment]
Follow the the installation process, then run tailwind in development mode.
if you get an error of no utilities where generated.... go to your tailwind.config.js file and update the content array
e.g

module.exports = {
  content: ["./screens/**/*.js", "./components/**/*.js", "./app/**/*.js"], 
  theme: {
    extend: {},
  },
  plugins: [],
};




 content: ["./screens/**/*.js", "./components/**/*.js", "./app/**/*.js"], 
Here the "./app/**/*.js" matches my project structure.


This is how i solved the problem hope it this will help you too.

**Comment by vyrru5** [comment]
Trying to test with expo on new project for rn v4.0, that not clear don't work, 
tailwind.css blank

on v3.0.1 with expo works

**Comment by jamesvsshark** [comment]
Just confirmed this does work.

Thank you @ilyapas 

Should someone open a PR to update the docs to add this messing step?

**Comment by Pramuspl** [comment]
of course, remember to use `content: ["./screens//*.{ts,tsx}", "./components//*.{ts,tsx}"],` instead if in a TypeScript project.

**Comment by vadimdemedes** [comment]
@camillo18tre `grid-*` utilities aren't supported (see ["Supported Utilities"](https://github.com/vadimdemedes/tailwind-rn#supported-utilities) section in the readme), that's why you're getting "Unsupported Tailwind class" error.

As for the supported utilities, @ilyapas is right, you must configure `content` in your `tailwind.config.js`, which is described in both the readme and `setup-tailwind-rn` CLI.

**Comment by baoanhng** [comment]
Can we have a big notice about adding content rules?
