### ISSUE TITLE
Toggle dark mode manually

### ISSUE THREAD

**Issue by HeleneGrini** [vadimdemedes/tailwind-rn#125]
The current `tailwind-rn` only supports dark mode when it set on the system OS. It would be nice to have support for passing color scheme to the TailwindProvider to enable manually toggling color scheme. Any plans to add this or should I make a PR?

**Comment by vadimdemedes** [comment]
Good idea! Yep, a PR is always appreciated.

I think we could add `colorScheme` property to `TailwindProvider`. When it's set, we'd ignore the output of [`useColorScheme`](https://github.com/vadimdemedes/tailwind-rn/blob/master/source/tailwind-provider.tsx#L17)  when [creating a `tailwind`](https://github.com/vadimdemedes/tailwind-rn/blob/master/source/tailwind-provider.tsx#L25-L31) function. You can also reuse the type for `colorScheme` property from https://github.com/vadimdemedes/tailwind-rn/blob/master/source/types.ts#L12.
