### ISSUE TITLE
tailwind.json file is empty after rebuild

### ISSUE THREAD

**Issue by timbastin** [vadimdemedes/tailwind-rn#130]
First, thanks for this project and all the work!
I am encountering a bugging issue. When I start the CLI using the provided command: `concurrently \"tailwindcss --input input.css --output tailwind.css --no-autoprefixer --watch\" \"tailwind-rn --watch\"` everything runs fine. The `tailwind.css` file gets generated correctly and the `tailwind.json` file has the expected content.

After adding a new style property which is **not** present in the already generated files, the CLI logs will display something like: `Rebuilding.... Done in 96ms`. The `tailwind.css` file does contain the new added property, but the `tailwind.json` file contains an empty JSON object (`{}`). The only fix for this is to start the CLI again. On the first build, everything gets generated correctly.

Did anyone already encounter this issue?

Here is my `tailwind.config.js`

```
module.exports = {
    content: ["./src/**/*.tsx"],
    corePlugins: {
        boxShadow: false,
        translate: false,
        transform: false,
        ringWidth: false
    },
    plugins: [],
};
```

I am using the latest expo SDK (44). The project uses typescript.

Thanks a lot!

**Comment by JamesPaing** [comment]
I am also having same issue in my expo typescript project, have you found any solution ?

**Comment by mjrdnk** [comment]
Same here.

**Comment by jonsamp** [comment]
I posted setup steps that are working for Expo SDK 44 here: https://github.com/vadimdemedes/tailwind-rn/issues/128#issuecomment-1019372506

**Comment by waynedunkley** [comment]
When you do the initial `yarn dev:tailwind` there will be no content in `tailwind.json` until you add styles within your codebase using `useTailwind()`. What got `yarn dev:tailwind` working for me. Was following @jonsamp instructions in the supplied link. Add an initial style in your codebase, run `yarn build:tailwind`, this will generate a style in your json file, then run `yarn dev:tailwind` to listen for further changes. Everything worked from this point on

**Comment by timbastin** [comment]
> When you do the initial yarn dev:tailwind there will be no content in tailwind.json until you add styles within your codebase using useTailwind(). 

There are styles within the codebase. The `tailwind.json` is generated correctly when running the initial `npm run dev:tailwind`.  (I am using NPM instead of yarn). It does contain the used styles.

> What got yarn dev:tailwind working for me. Was following @jonsamp instructions in the supplied link. Add an initial style in your codebase, run yarn build:tailwind, this will generate a style in your json file, then run yarn dev:tailwind to listen for further changes. Everything worked from this point on

I am afraid, even after installing PostCSS the issue does still persist: Whenever `tailwind-rn` encounters a **new** style (which is currently not used inside the codebase) the tailwind.json will only contain an empty JSON object (`{}`)

For me, it seems like a race condition...

**Comment by vadimdemedes** [comment]
Yeah, sounds like a race condition. I might delay `tailwind-rn`'s watch process by some time, so that it always generated `tailwind.json` from the latest `tailwind.css`. Will look into it.

**Comment by vadimdemedes** [comment]
Fixed via https://github.com/vadimdemedes/tailwind-rn/pull/136.
