### ISSUE TITLE
Unsupported Tailwind class

### ISSUE THREAD

**Issue by ceIia** [vadimdemedes/tailwind-rn#134]
Hey! I'm currently starting up a new project using `tailwind-rn`, `react-native` and `expo`,  however I'm facing a bit of a strange issue.

See, I've followed the setup guide to the letter, and I managed to get the library somewhat working, but on a lot of classes, it seems that it just doesn't work (whether i use `build:tailwind` or `dev:tailwind`).

Looking at the [tailwind.json](https://gist.github.com/69aba811a79e45d8207a188c95ee29b9) and the [tailwind.css](https://gist.github.com/2a834ca1c686bd2f6fffe5e587255648) (links attached), you can see a few classes being generated. However, I have no idea where these are coming from. For example, I'm not using `border-red-500` or `mb-1` anywhere yet, which makes me wonder why on earth would these classes get generated in the first place.

Taking a look at my `tailwind.config.js`, it would seem that everything is fine.
```js
module.exports = {
  content: ['./src/**/*.{tsx,ts)'],
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#F0F6FF',
          100: '#DBEAFF',
          200: '#B8D5FF',
          300: '#85B8FF',
          400: '#388BFF',
          500: '#004EBF',
          600: '#0046A8',
          700: '#004099',
          800: '#003580',
          900: '#002457'
        }
      },
      fontSize: {
        '5xl': '2.5rem'
      }
    }
  },
  plugins: [],
  corePlugins: { transform: false, translate: false, boxShadow: false }
};
```

The classes that are almost "randomly" generated in the tailwind.json/css are perfectly usable, such as `text-red-500`, but not the `text-4xl` that is currently being applied to the same `<Text>`:
![image](https://user-images.githubusercontent.com/25929147/150886659-435252b1-635a-465f-afd5-6bd2206c8f92.png)

Here is also a link to my [package.json](https://gist.github.com/cc70d6a8c9dd256e1ad61dbab9da35c9).

**Comment by Horsty80** [comment]
Hi @ceIia , not the good way but I actually use `safelist` to generate my customs classes with `pattern` matcher
Maybe it's can help you to do the same thing for your font-size

Here is an example that I use on my project
```js
module.exports = {
  safelist: [
    "bg-primary",
    "bg-secondary",
    "bg-info",
    "bg-alert",
    "bg-dark",
    "bg-disabled",
    "bg-placeHolder",
    "bg-success",
    {
      pattern: /bg-uhue-(red|green|orange|blue)-\d{3}/,
    },
  ],
  theme: {
    extend: {
      colors: {
        primary: "#8abdf6",
        secondary: "#F6C38A",
        success: "#3FC5A3",
        error: "#c53f61",
        dark: "#11162C",
        disabled: "#57627B",
        placeHolder: "#8F9BB3",

        "uhue-red": {
          100: "#f9ebef",
          200: "#f3d8df",
          300: "#edc5cf",
          400: "#e7b2bf",
          500: "#e29fb0",
          600: "#dc8ba0",
          700: "#d67890",
          800: "#d06580",
          900: "#ca5270",
        },
        "uhue-green": {
          100: "#ebf9f5",
          200: "#d8f3ec",
          300: "#c5ede3",
          400: "#b2e7da",
          500: "#9fe2d1",
          600: "#8bdcc7",
          700: "#78d6be",
          800: "#65d0b5",
          900: "#52caac",
        },
        "uhue-orange": {
          100: "#fef9f3",
          200: "#fdf3e7",
          300: "#fceddb",
          400: "#fbe7d0",
          500: "#fae1c4",
          600: "#f9dbb8",
          700: "#f8d5ad",
          800: "#f7cfa1",
          900: "#f6c995",
        },
        "uhue-blue": {
          100: "#f3f8fe",
          200: "#e7f1fd",
          300: "#dbebfc",
          400: "#d0e4fb",
          500: "#c4defa",
          600: "#b8d7f9",
          700: "#add0f8",
          800: "#a1caf7",
          900: "#95c3f6",
        },
      },
    },
  },
};
```

Hope it's can help you.

From the doc of tailwind :

> Safelisting is a last-resort, and should only be used in situations where it’s impossible to scan certain content for class names. These situations are rare, and you should almost never need this feature.
If you need to make sure Tailwind generates certain class names that don’t exist in your content files, use the safelist option:
 
[Safelisting classes](https://tailwindcss.com/docs/content-configuration#safelisting-classes)

**Comment by vadimdemedes** [comment]
Hey @ceIia, would you be able to create a repository with a minimal reproduction of your issue? Not sure what's going on here based on the current information.

**Comment by kxxoling** [comment]
Same issue here. I've created a fresh new project and encountered the same issue.

This is my App.tsx:

```tsx
import {
  Colors,
  DebugInstructions,
  Header,
  LearnMoreLinks,
  ReloadInstructions,
} from 'react-native/Libraries/NewAppScreen';
import {
  SafeAreaView,
  ScrollView,
  StatusBar,
  StyleSheet,
  Text,
  View,
  useColorScheme,
} from 'react-native';
import {TailwindProvider, useTailwind} from 'tailwind-rn';

import React from 'react';
import utilities from './tailwind.json';

const Section: React.FC<{
  title: string;
}> = ({children, title}) => {
  const isDarkMode = useColorScheme() === 'dark';
  return (
    <View style={styles.sectionContainer}>
      <Text
        style={[
          styles.sectionTitle,
          {
            color: isDarkMode ? Colors.white : Colors.black,
          },
        ]}>
        {title}
      </Text>
      <Text
        style={[
          styles.sectionDescription,
          {
            color: isDarkMode ? Colors.light : Colors.dark,
          },
        ]}>
        {children}
      </Text>
    </View>
  );
};

const CustomHeader = () => {
  const tailwind = useTailwind();
  return <Text style={tailwind('bg-primary')}>custom header3</Text>;
};

const App = () => {
  const isDarkMode = useColorScheme() === 'dark';

  const backgroundStyle = {
    backgroundColor: isDarkMode ? Colors.darker : Colors.lighter,
  };

  return (
    <TailwindProvider utilities={utilities}>
      <SafeAreaView style={backgroundStyle}>
        <StatusBar barStyle={isDarkMode ? 'light-content' : 'dark-content'} />
        <ScrollView
          contentInsetAdjustmentBehavior="automatic"
          style={backgroundStyle}>
          <CustomHeader />
          <Header />
          <View
            style={{
              backgroundColor: isDarkMode ? Colors.black : Colors.white,
            }}>
            <Section title="Step One">
              Edit <Text style={styles.highlight}>App.tsx</Text> to change this
              screen and then come back to see your edits.
            </Section>
            <Section title="See Your Changes">
              <ReloadInstructions />
            </Section>
            <Section title="Debug">
              <DebugInstructions />
            </Section>
            <Section title="Learn More">
              Read the docs to discover what to do next:
            </Section>
            <LearnMoreLinks />
          </View>
        </ScrollView>
      </SafeAreaView>
    </TailwindProvider>
  );
};

const styles = StyleSheet.create({
  sectionContainer: {
    marginTop: 32,
    paddingHorizontal: 24,
  },
  sectionTitle: {
    fontSize: 24,
    fontWeight: '600',
  },
  sectionDescription: {
    marginTop: 8,
    fontSize: 18,
    fontWeight: '400',
  },
  highlight: {
    fontWeight: '700',
  },
});

export default App;
```

And all the configs are updated by `npx setup-tailwind-rn`

**Comment by grrbm** [comment]
Same thing happens on Windows with expo running tailwind-rn on android

**Comment by cupliz** [comment]
here is my content to get it working 
`module.exports = {
  mode: 'jit',
  content: ['./src/**/*.js'],
  theme: {
    extend: {},
  },
  plugins: [],
  corePlugins: require('tailwind-rn/unsupported-core-plugins'),
}
`

create `src` directory and move App.js to `/src/App.js`

**Comment by cupliz** [comment]
Here is my `tailwind.config.js`
```
module.exports = {
  mode: 'jit',
  content: ['./src/**/*.js'],
  theme: {
    extend: {},
  },
  plugins: [],
  corePlugins: require('tailwind-rn/unsupported-core-plugins'),
}
```

Create `src` directory and move App.js to `/src/App.js`

**Comment by grrbm** [comment]
celia did you fix it ?

**Comment by ceIia** [comment]
Yeah. Keep in mind that `text-${color}-500` won't work. Literal class names only.

**Comment by grrbm** [comment]
So the solution was to use "safelist" as Horsty80 mentioned ?

**Comment by ceIia** [comment]
No, I'm not too fond of this. Instead I went with something that ressembles this:
```
<Text style={tailwind({small: 'text-xs', large: 'text-xl'}[size] />
```

This is a basic example but you can easily adapt it to your needs by moving the object higher for more complex uses, or even using `clsx()`. :)

**Comment by grrbm** [comment]
neat ! :)
