### ISSUE TITLE
Is there any guidance for getting this working within nx workspaces?

### ISSUE THREAD

**Issue by jasonhjohnson** [vadimdemedes/tailwind-rn#135]

**Comment by Maruf97103** [comment]
I use this package with nx but i can't generate the tailwind.json file

**Comment by jasonhjohnson** [comment]
@Maruf97103 Yeah, I did the following to get it to _almost_ work:

1. Ran `yarn add tailwind-rn` (and concurrently and tailwindcss and postcss for some reason) from the root workspace
2. Within the actual react native app project off of the root of the workspace (_/apps/mobile_) ran the `npx setup-tailwind-rn` which did some magic, creating the tailwind config files and adding some script commands to my _/apps/mobile/package.json_ 
3. I had to point the `content` node in the `tailwind.config.js` to look at my source files like:
```
module.exports = {
  content: [
    './src/**/*.{html,js,tsx}',
  ] // ... 
  ```
4. I also ran `yarn dev:tailwind` from _/apps/mobile_ and it generated my tailwind.json and tailwind.css

In the end, if I use any tailwind css in my components it updates the tailwind.json and tailwind.css file correctly but I **_don't_** see the styles visually reflected in my app. I'm sure I configured something wrong.

Curious to hear how you set things up

**Comment by Maruf97103** [comment]
Hey @jasonhjohnson , i did that process as well, i don't see styles too, but i have problem with multi theme. do you have any idea how to make my app to support multi theme.

**Comment by vadimdemedes** [comment]
I have no idea what nx workspaces are, so I'd appreciate help from someone who does!

**Comment by Horsty80** [comment]
@jasonhjohnson have you some code to share / error / jsfiddle and co to help you ? 

Like @vadimdemedes I don't know nx Workspaces.

The Vadim's Lib is working with expo and react-native setup, so I don't see why isn't working with other setup.
For this kind of issue maybe you need to open an issue on the Nx Workspaces side.

**Comment by jasonhjohnson** [comment]
@Horsty80 Thanks for being willing to help despite my lack of context. I don't really have code to share. 

Essentially nx allows for your to share libraries/code in one monorepo in a convenient way (in addition to other things). You install all of your dependencies at the root workspace level and subsequent projects (in this case my react native project) is installed as a sub project/folder within the workspace. So, there's some bit of finesse that needs to happen when setting up `tailwind-rn` in this structure so that we can, from the ROOT workspace, install it, configure (and run) it's build scripts and configure tailwind...and then have the output (tailwind.json and tailwind.css) placed into the sub folder containing the react-native project. That is happening for me, it's just that the styles aren't being reflected visually in my UI. I'm 99% sure I'm missing something obvious and I'll keep poking around and comment here if I find where I went astray.

**Comment by potb** [comment]
I've just created a repository to show how to use tailwind-rn into an nx workspace : https://github.com/potb/nx-tailwind-rn.
If you have any suggestion or question, feel free to open a pr or an issue.

**Comment by jasonhjohnson** [comment]
@potb You are awesome! Thank you!

**Comment by vadimdemedes** [comment]
Thanks @potb! Going to close this now, looks like it's resolved ;)
