### ISSUE TITLE
Is tailwind-rn reaching into a private internal file of react-native instead of using the public API ?

### ISSUE THREAD

**Issue by gablabelle** [vadimdemedes/tailwind-rn#138]
Hello,

I'm trying to setup `tailwind-rn` in a next.js + expo monorepo (using react-native-web) and after adding `tailwind-rn` to my list of next-transpile-modules I still get the following error.

<img width="1008" alt="Screen Shot 2022-01-29 at 14 16 34" src="https://user-images.githubusercontent.com/1565793/151674580-cd7fefa8-296d-40ca-93eb-a9e15c8893d1.png">

It throws that error trying to parse a Flow file. Could it be that the `tailwind-rn` lib is [is reaching into a private internal file of react-native](https://github.com/necolas/react-native-web/issues/1812#issuecomment-729099067) instead of using the public API ?

**Comment by asader** [comment]
I've got same error. Trying to add tailwind-rn in react-native-web-monorepo

**Comment by vadimdemedes** [comment]
Nope, it doesn't access any private APIs or files.

What made you think it's related to `tailwind-rn`?

**Comment by asader** [comment]
This error happens because of hooks used in tailwind-provider.tsx. I was able to make it work, by putting calls of Dimensions methods in useEffect(() => , [])

`
import {
	useDimensions,
	useAccessibilityInfo,
	useDeviceOrientation
} from '@react-native-community/hooks';
`

**Comment by vadimdemedes** [comment]
Not sure what you mean, `tailwind-rn` uses `useDimensions` hook, which can't be placed inside a `useEffect`.

**Comment by asader** [comment]
I'm talking about code inside useDimensions hook. Here's my server side friendly version of useDemensions hook

`
import {useEffect, useState} from 'react';
import {Dimensions, ScaledSize} from 'react-native';

export function useDimensions() {
	const [dimensions, setDimensions] = useState({
		window: {} as ScaledSize,
		screen: {} as ScaledSize
	});

	const onChange = ({
		window,
		screen
	}: {
		window: ScaledSize;
		screen: ScaledSize;
	}) => {
		setDimensions({window, screen});
	};

	useEffect(() => {
		const subscription = Dimensions.addEventListener('change', onChange);

		setDimensions({
			window: Dimensions.get('window'),
			screen: Dimensions.get('screen')
		});
		return () => {
			// eslint-disable-next-line @typescript-eslint/ban-ts-comment
			// @ts-ignore
			if (typeof subscription?.remove === 'function') {
				// eslint-disable-next-line @typescript-eslint/ban-ts-comment
				// @ts-ignore
				subscription.remove();
			} else {
				// React Native < 0.65
				Dimensions.removeEventListener('change', onChange);
			}
		};
	}, []);

	return dimensions;
}
`

**Comment by vadimdemedes** [comment]
I see, then this isn't a `tailwind-rn` issue. I guess [`@react-native-community/hooks`](https://github.com/react-native-community/hooks) isn't compatible with react-native-web, but you should ask them to confirm.

**Comment by gablabelle** [comment]
@asader If you're using next.js you can fix this by adding `@react-native-community/hooks` to list of transpiled modules and it now works.

```
const withTM = require('next-transpile-modules')([
  'tailwind-rn',
  '@react-native-community/hooks',
]);
```
