### ISSUE TITLE
Pseudo-classes not available

### ISSUE THREAD

**Issue by mohibkay** [vadimdemedes/tailwind-rn#141]
I am using tailwind-rn with Expo for web with react-native components (https://docs.expo.dev/guides/using-nextjs/). 
Where I am using the same react-native components to run on Expo Nextjs, ios, and android app.

Tailwind-rn v4.0.1 is working, however, pseudo-classes like hover, focus are not available.

Is there a way to add them?

**Comment by vadimdemedes** [comment]
Aren't they unsupported in react-native-web?

**Comment by langtube** [comment]
@vadimdemedes I think it's [this line of code](https://github.com/vadimdemedes/tailwind-rn/blob/9f3cddd9574045c97bc9e71573d030694b6a781a/source/build.ts#L19) that removes the pseudo-classes.

**Comment by vadimdemedes** [comment]
I decided this package will target React Native and won't support React Native Web. Otherwise `tailwind-rn` wouldn't be able to detect unsupported utilities, which would result in a worse developer experience.
