### ISSUE TITLE
useTailwind in React class component

### ISSUE THREAD

**Issue by Gregoirevda** [vadimdemedes/tailwind-rn#142]
I need to use tailwind in a custom Animated component, which requires the component to be a class.
`Animated.createAnimatedComponent(ClassComponent)`

```javascript
class ClassComponent extends React.Component {
  static contextType = ThemeContext;
  render() {
    return <Button theme={this.context} />;
  }
}
```

Could you export the context?

`export {default as TailwindContext} from './tailwind-context';`

**Comment by vadimdemedes** [comment]
Could you share what exactly requires your component to be a class?

**Comment by Gregoirevda** [comment]
React Native `Animated.createAnimatedComponent` requires the component the be a class

**Comment by vadimdemedes** [comment]
Looks like there's a workaround that involves wrapping your function component into a class one → https://github.com/software-mansion/react-native-reanimated/discussions/1527. Would that work for you?

**Comment by Gregoirevda** [comment]
It could, but I don't want to wrap all class components in an extra call to access context.
If class component need access to the Context, I guess it means it's fine for it to be public

**Comment by vadimdemedes** [comment]
Have you checked the discussion I sent a link to? It has a code snippet for a function you can use, which wraps function components into classes for you.

**Comment by Gregoirevda** [comment]
Yes, but I find it cleaner to not wrap a function component with another useless class (just to be able to use a hook) and instead use the context directly.
[here](https://github.com/software-mansion/react-native-screens/blob/6c87d7749ec62fbb51fb4ec50af1fa8733ebae86/src/native-stack/index.tsx#L15) is an example of an exported context (next to an exported `useHeaderHeight` hook) in a popular library

**Comment by vadimdemedes** [comment]
`TailwindContext` is an internal component of `tailwind-rn`, so I'm hesitant to expose it as a public API. It'd make it harder for me to make changes to how `tailwind-rn` works, because there's no control over how `TailwindContext` is consumed, compared to `useTailwind` hook.

This issue should really be fixed in React Native instead, because as mentioned in the discussion I linked, there's no evidence that class components are required.

Until it's fixed there, you can try wrapping your function component or pass `tailwind` function as a prop:

```jsx
const MyAnimatedComponent = Animated.createAnimatedComponent(MyComponent);

const App = () => {
	const tailwind = useTailwind();
	return <MyAnimatedComponent tailwind={tailwind}/>;
};
```

**Comment by visormatt** [comment]
@Gregoirevda while it's not formally exposed (directly at least) you can still access access the context, here's a simple example that may help vs. having to wrap it. 

```tsx
import * as React from 'react';
import TailwindContext from 'tailwind-rn/dist/tailwind-context';

export class TailwindWithClassComponents extends React.Component {
  static contextType = TailwindContext;

  render() {
    const tailwind = this.context;
    console.log('--> this.context', this.context);

    return <Text style={tailwind('uppercase')}>Testing...</Text>;
  }
}
```
