### ISSUE TITLE
tailwind is Not working  used version is 4.2.0

### ISSUE THREAD

**Issue by infofauna** [vadimdemedes/tailwind-rn#146]
Dear all,

I have created an expo app using typescript then I followed the steps  step by step:

  ↓ What's next?

  1. Run tailwind-rn in development mode:

   $ yarn dev:tailwind

  2. Import TailwindProvider and tailwind.json in the root of your app

   import {TailwindProvider} from 'tailwind-rn';
   import utilities from './tailwind.json';

  3. Wrap the root of your app into TailwindProvider:

   <TailwindProvider utilities={utilities}>
     <MyComponent/>
   </TailwindProvider>

  4. Use Tailwind

   import {useTailwind} from 'tailwind-rn';

   const MyComponent = () => {
     const tailwind = useTailwind();

     return <Text style={tailwind('text-blue-600')}>Hello world</Text>;
   };
But unfortunately the tailwind is not working at all .
could you please share a sample that works ??

many thanks

**Comment by bakydev** [comment]
- Source code where I have `tailwind-rn` is used:
`import { useTailwind } from 'tailwind-rn'

export default function SampleScreen() {
   const tailwind = useTailwind()

   return (
      <Text style={tailwind('text-blue-600')}>Hello world</Text>
   )
}
`

- Command that I used is `"dev:tailwind": "concurrently \"tailwindcss --input input.css --output tailwind.css --no-autoprefixer --watch\" \"tailwind-rn --watch\""`

- Content of `tailwind.css` is:
`*, ::before, ::after {
  --tw-ordinal:  ;
  --tw-slashed-zero:  ;
  --tw-numeric-figure:  ;
  --tw-numeric-spacing:  ;
  --tw-numeric-fraction:  
}`

- Content of `tailwind.json` is:
`{
	"*": {
		"style": {
			"--tw-ordinal": "",
			"--tw-slashed-zero": "",
			"--tw-numeric-figure": "",
			"--tw-numeric-spacing": "",
			"--tw-numeric-fraction": ""
		}
	},
	"::before": {
		"style": {
			"--tw-ordinal": "",
			"--tw-slashed-zero": "",
			"--tw-numeric-figure": "",
			"--tw-numeric-spacing": "",
			"--tw-numeric-fraction": ""
		}
	},
	"::after": {
		"style": {
			"--tw-ordinal": "",
			"--tw-slashed-zero": "",
			"--tw-numeric-figure": "",
			"--tw-numeric-spacing": "",
			"--tw-numeric-fraction": ""
		}
	}
}`

- Tailwind CSS config from `tailwind.config.js` is:
`module.exports = {
  content: [
    './src/screens/*.{js}',
    './src/components/*.{js}',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
  corePlugins: require('tailwind-rn/unsupported-core-plugins'),
}
`

**Comment by vadimdemedes** [comment]
Could you show your `input.css`? Have you added `TailwindProvider` to the root of your app?

**Comment by bakydev** [comment]
My `input.css`:
```
@tailwind base;
@tailwind components;
@tailwind utilities;
```

My `App.js`:
```
import 'react-native-gesture-handler';
import React from 'react';
import { NavigationContainer } from '@react-navigation/native';
import NavigationBottombar from './src/navigations/NavigationBottomBar';
import { AuthProvider } from './src/features/auth';
import { TailwindProvider } from 'tailwind-rn';
import utilities from './tailwind.json';

const App = () => {

  return (
    <AuthProvider>
      <TailwindProvider utilities={utilities}>
        <NavigationContainer>
          <NavigationBottombar />
        </NavigationContainer>
      </TailwindProvider>
    </AuthProvider>
  );
}

export default App;
```

**Comment by ridhwaanm** [comment]
> dev:tailwind

When running the development in the terminal do you just run "expo start" or "dev:tailwind"? I get "dev:tailwind: The term 'dev:tailwind' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again." when I try to run it.

**Comment by vadimdemedes** [comment]
@bakydev `input.css` should only contain `@tailwind utilities;`. Also, make sure to double-check if `content` covers all your project files where `tailwind-rn` is used.

@ridhwaanm It should be `npm run dev:tailwind`, because it's an npm script and not a program installed in your system.

**Comment by bakydev** [comment]
@vadimdemedes I did, it does not help.
My `input.css` only contain one line:
`@tailwind utilities `.
I’m just testing tailwind on my /screen folder how does it work. So if It will be work, of course I will move my styles to /components folder

**Comment by kanso-git** [comment]
This is an example with tailwind css version 4.2.0^
https://github.com/kanso-git/my-app-rn

I hope that helps

**Comment by bakydev** [comment]
@kanso-git I have the same code, so the problem I think in the script when I’m running yarn run dev:tailwind, but in the terminal written builded

**Comment by bakydev** [comment]
I found the problem, btw thank you guys

**Comment by vadimdemedes** [comment]
What was the problem?

**Comment by bakydev** [comment]
@vadimdemedes
I don't know, something magical happened.
I just stopped all of my scripts and started again solved everything.

**Comment by rahmor** [comment]
Had this issue today.  Used import tailwind from 'tailwind-rn'.  When I tried to log the tailwind import for some reason it came back as undefined. Used version 3.0.1 instead and it worked.
