### ISSUE TITLE
Support PlatformColor api

### ISSUE THREAD

**Issue by Gregoirevda** [vadimdemedes/tailwind-rn#147]
It would be nice if the library could support [PlatformColor](https://reactnative.dev/docs/platformcolor) api.

By providing system colors in the tailwind.config.js
```javascript
colors: {
   label: PlatformColor('label', '?android:attr/textColor')
 }
```

and usage
```javascript
<View style={tw('text-label')} />
```

Light and dark mode would then be handled on the native end

**Comment by vadimdemedes** [comment]
Since it's not part of Tailwind itself, I don't think it'd be the right move to include it in `tailwind-rn`. Workaround is to add the custom utilities yourself, like this:

```jsx
import utilities from './tailwind.json';

<TailwindProvider utilities={{
	...utilities,
	'my-custom-utility': {
		style: {
			color: '#my-custom-color'
		}
	}
}}/>
```
