### ISSUE TITLE
Code completion

### ISSUE THREAD

**Issue by kanso-git** [vadimdemedes/tailwind-rn#149]
I wondered how to enable code completion like in the web development .
many thanks in advance for your help
![image](https://user-images.githubusercontent.com/2843192/153390454-95781877-4042-4601-b13a-39cfe33dc542.png)

**Comment by danddanddand** [comment]
Same thing was frustrating me and I started using [Tabnine](https://www.tabnine.com/) Plugin and after about a week it was giving me very very good suggestions for tailwind. It's not perfect but was surprisingly good.
