### ISSUE TITLE
Typed classnames for autocompletion

### ISSUE THREAD

**Issue by ecklf** [vadimdemedes/tailwind-rn#15]
I like this API the most from the available Tailwind / RN projects but it's a bit sad to lose the ability for auto-completion. 

What about going from this:
```jsx
tailwind('bg-blue-200 px-3 py-1 rounded-full')
```
to something like this:
```jsx
tailwind('bg-blue-200', 'px-3', 'py-1', 'rounded-full')
```

**Comment by matepapp** [comment]
I have an idea of how to support a typed API, but we have to migrate to TypeScript in that case. From TypeScript 2.9 you can import JSON modules in TS files with full typed support. We can create a `tailwind()` method where we expose the keys of the JSON and get amazing autocompletion and type-safety ✨ 

<img width="687" alt="Screenshot 2020-05-19 at 16 39 32" src="https://user-images.githubusercontent.com/17027165/82341486-c4bad200-99f0-11ea-97e3-3b3f138a9f88.png">

<img width="686" alt="Screenshot 2020-05-19 at 16 39 57" src="https://user-images.githubusercontent.com/17027165/82341530-d69c7500-99f0-11ea-8473-7151e7d03cf5.png">

**Comment by impulse** [comment]
@matepapp nice find! 

However, I can't think of a sensible TypeScript solution that would not require the API change I mentioned above. Your current implementation would only allow one className in the `tailwind` function unless you generate all combinations of className strings.

My proposal would look something like this:

```ts
import JSON from "./styles.json";
type Keys = keyof typeof JSON;

const tailwind = (...props: Keys[]) => {
  return props.reduce(
    (styles, curr) => ({
      ...styles,
      ...JSON[curr],
    }),
    {}
  );
}
```
![image](https://user-images.githubusercontent.com/8146736/82354994-e7091b80-9a01-11ea-8411-98e5d3264d4d.png)

**Comment by matepapp** [comment]
Yes, this was only just a quick example to demonstrate the possibility of type-safety. Your solution is definitely a step ahead, but I think we should support regular `string` type as well to keep the API backward compatible. Switching based on the type could be a temporary workaround. What do you think?

I might can create a draft pull request next week if it’s okay for you @vadimdemedes

**Comment by impulse** [comment]
Well we could either add an additional function to the core or add readme instructions on how to achieve this with a custom tailwind function (would be neat if `useVariables` would get exported then).

**Comment by vadimdemedes** [comment]
@matepapp Yeah, I think something like that would work. Would be still great to preserve support for specifying multiple classes in one string for people that don't care about autocomplete (like me).

The only thing I'm wondering about is how will it work with custom configs?

**Comment by tommulkins** [comment]
@vadimdemedes You may be interested in following this Tailwind Intellisense issue (https://github.com/tailwindcss/intellisense/issues/129) in regards to this.

**Comment by vadimdemedes** [comment]
@tommulkins Thanks for linking it here!

**Comment by leggomuhgreggo** [comment]
I think this might have just become more feasible with the improvements in TS 4.1

https://twitter.com/diegohaz/status/1309489079378219009

**Comment by gitstud** [comment]
Is there a PR on the horizon for this?

**Comment by gitstud** [comment]
Is there a PR on the horizon for this?

**Comment by impulse** [comment]
There is now a way to achieve this with the official VSCode extension.
https://twitter.com/ecklflorentin/status/1344242188574720000

**Comment by jonlambert** [comment]
For those who want a quick copy and paste:

```json
"tailwindCSS.experimental.classRegex": ["tailwind\\('|\"([^'|\")]*)"]
```

^ add to your VS Code `settings.json` file. I've adjusted the regex to pick up single or double quotes.

**Comment by tommulkins** [comment]
To make intellisense work in a tailwind-rn project, i.e. `style={tailwind('mb-1')}` I use the following:

```
  /* TailwindCSS */
  "tailwindCSS.experimental.classRegex": ["tailwind\\('([^)]*)\\')", "'([^']*)'"]
  ```

**Comment by ecklf** [comment]
I think we can close this issue 👍🏻

**Comment by lyzMaster** [comment]
I must run `npm install tailwindcss` to have Tailwind CSS IntelliSense autocomplete feature, can I ignore this step?

**Comment by ecklf** [comment]
> I must run `npm install tailwindcss` to have Tailwind CSS IntelliSense autocomplete feature, can I ignore this step?

Afaik you only need a tailwind.config.js in your project root for IntelliSense to work.

**Comment by tommulkins** [comment]
> I must run `npm install tailwindcss` to have Tailwind CSS IntelliSense autocomplete feature, can I ignore this step?

You can run `npx tailwindcss init` instead to make your tailwind.config.js file.

**Comment by lyzMaster** [comment]
> > I must run `npm install tailwindcss` to have Tailwind CSS IntelliSense autocomplete feature, can I ignore this step?
> 
> You can run `npx tailwindcss init` instead to make your tailwind.config.js file.

Before this, I have run `npx tailwindcss init` and so I got `tailwind.config.js`, but IntelliSense still not work and I got this error in the `OUTPUT` of vscode(I tried restarting vscode):
<img width="1094" alt="截屏2021-06-24 上午11 58 26" src="https://user-images.githubusercontent.com/12180730/123200531-7e814d80-d4e3-11eb-8005-c3a215fa90ae.png">

And I check out doc of Tailwindcss IntelliSense, which says: `In order for the extension to activate you must have tailwindcss installed and a Tailwind config file named tailwind.config.js in your workspace.`. So I try `npm install tailwindcss`, and after restarting vscode, autocomplete works. So I guess maybe IntelliSense check `package.json -> dependencies`, if "tailwindcss" in dependencies, IntelliSense works?

**Comment by ecklf** [comment]
Seems you need to have it installed then. Note that the autocomplete will adhere to your tailwind configuration and not to `tailwind-rn`'s compatibility limitations. You can disable core plugins for this.

**Comment by harshjadon9** [comment]
> To make intellisense work in a tailwind-rn project, i.e. `style={tailwind('mb-1')}` I use the following:
> 
> ```
>   /* TailwindCSS */
>   "tailwindCSS.experimental.classRegex": ["tailwind\\('([^)]*)\\')", "'([^']*)'"]
> ```

### this isn't working for me...
i have pasted the above in setting.json

My **tailwind.js**
```
import { create } from 'tailwind-rn';
import styles from '../styles.json';

const { tailwind, getColor } = create(styles);
export { tailwind, getColor };
```

My **home.js**
```
...
import { getColor, tailwind } from '../tailwind';

const home = () =>{
    return(
        <View>
            <Text>hi there</Text>
            <Text style={tailwind('mb-1')}>hi there</Text>
        </View>
    )
}

export default home
```

 @tommulkins , @jonlambert  or anyone could please resolve this

**Comment by tommulkins** [comment]
> > To make intellisense work in a tailwind-rn project, i.e. `style={tailwind('mb-1')}` I use the following:
> > ```
> >   /* TailwindCSS */
> >   "tailwindCSS.experimental.classRegex": ["tailwind\\('([^)]*)\\')", "'([^']*)'"]
> > ```
> 
> ### this isn't working for me...
> i have pasted the above in setting.json
> 
> My **tailwind.js**
> 
> ```
> import { create } from 'tailwind-rn';
> import styles from '../styles.json';
> 
> const { tailwind, getColor } = create(styles);
> export { tailwind, getColor };
> ```
> 
> My **home.js**
> 
> ```
> ...
> import { getColor, tailwind } from '../tailwind';
> 
> const home = () =>{
>     return(
>         <View>
>             <Text>hi there</Text>
>             <Text style={tailwind('mb-1')}>hi there</Text>
>         </View>
>     )
> }
> 
> export default home
> ```
> 
> @tommulkins , @jonlambert or anyone could please resolve this

I currently use _tailwind-react-native-classnames_ with the following regex settings in my project:
 
_vscode/settings.json_
```
{
  /* TailwindCSS */
  "tailwindCSS.experimental.classRegex": [
    "tw`([^`]*)",
    "`([^`]*)",
    ["tw.style\\(([^)]*)\\)", "'([^']*)'"]
  ]
}
```
I believe that last value in the array will do the trick, `"'([^']*)'"`
