### ISSUE TITLE
All development is paused until Ukraine wins the war against russia

### ISSUE THREAD

**Issue by vadimdemedes** [vadimdemedes/tailwind-rn#158]
If you'd like to support Ukraine to win this war sooner, donate to ["Come Back Alive" organization](https://www.comebackalive.in.ua/donate).

**Comment by ianwijma** [comment]
Stay safe out there!

**Comment by vadimdemedes** [comment]
Thank you ❤️

**Comment by Ziao** [comment]
Completely understand. Your work is greatly appreciated. Stay safe my dude!

**Comment by cosmic-fox** [comment]
You guys are so amazing, thank you for all of your incredible contributions to the community. Stay safe <3

**Comment by devpenzil** [comment]
❤️

**Comment by devpenzil** [comment]
Stay safe

**Comment by vadimdemedes** [comment]
Hey folks, I'm going back to open source soon, so I just wanted to drop you a note that Ink will get updates soon. Thanks for everyone's understanding and patience, you're the best!

**Comment by Nikola-Milovic** [comment]
Stay safe! Glad to have you back

**Comment by kelvinndmo** [comment]
Welcome back @vadimdemedes , Stay Safe and are still wishing Ukraine the best
