### ISSUE TITLE
Support custom Tailwind config

### ISSUE THREAD

**Issue by branislaav** [vadimdemedes/tailwind-rn#16]
I created custom config with colors like `grey-900` but they where removed from styles.json.
I found this line in build.js `/^bg-(transparent|black|white|gray|red|orange|yellow|green|teal|blue|indigo|purple|pink)/`
I think it should be like this `/^bg-/`

**Comment by karolsw3** [comment]
You're right. I've checked that and it works now.

**Comment by vadimdemedes** [comment]
It can't be `/^bg-/`, because then it would include classes that are not supported in React Native, like `bg-repeat`.

As a workaround, I'd suggest using `gray` naming for now.

**Comment by vadimdemedes** [comment]
Actually, it could allow `bg-*` classes, but filter out unsupported ones, but I think it will be a super ugly regex to have.

**Comment by craigcartmell** [comment]
Is this also what's causing e.g. `primary`, `secondary`, `danger` etc from being removed from `bg-*` styles? I can see it's still generating`text-primary` for example, just not `bg-primary`.

**Comment by vadimdemedes** [comment]
Going to repurpose this into a generic issue on supporting custom Tailwind configs. I've started working on this, because it's clearly a much needed feature for the community.

**Comment by vadimdemedes** [comment]
Pushed https://github.com/vadimdemedes/tailwind-rn/pull/43 to support full customization of your Tailwind build. Try it out and let me know if it works or not!

**Comment by tvarwig** [comment]
@vadimdemedes your `custom-config` branch did create a custom `bg-xx` class great

**Comment by MaganAnkur** [comment]
@vadimdemedes i recently installed the library but still could not get custom bg-xx
Note: border and text are working as expected, issue is only with bg

**Comment by tvarwig** [comment]
@MaganAnkur did you use the `custom-config` branch? I added `primary` color to my config and `bg-primary` was added to the `styles.json` file

**Comment by aswinmohanme** [comment]
`custom-config` branch works for generating `bg-*`  classes

**Comment by vadimdemedes** [comment]
Closing, `tailwind-rn` supports custom config out of the box now.
