### ISSUE TITLE
How add custom font family?

### ISSUE THREAD

**Issue by albertcito** [vadimdemedes/tailwind-rn#160]
I installed a font using expo in this [way](https://docs.expo.dev/guides/using-custom-fonts/). It works

```typescript
<Text style={{ fontFamily: 'Inter_900Black'  }}>Inter Black</Text>
```

Now I updated `tailwind.config.js` in [this way](https://tailwindcss.com/docs/font-family#customizing-your-theme):
```javascript
module.exports = {
  content: [
    "./**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        'inter-black': ['Inter_900Black'],
      },
    },
  },
  plugins: [],
  corePlugins: require('tailwind-rn/unsupported-core-plugins'),
}
```

So I updated the style. But I'm getting the error: `Unsupported Tailwind class: "inter-black"`

```typescript
<Text style={tailwind('inter-black') }>
  Inter Black
</Text>
```

Also, I tried in [this way](https://tailwindcss.com/docs/font-family#customizing-the-default-font), but same message:

```javascript
module.exports = {
  content: [
    "./**/*.{ts,tsx}",
  ],
  theme: {
    fontFamily: {
      'inter-light': ['Inter_300Light'],
      'inter-black': ['Inter_900Black'],
    },
    extend: {},
  },
  plugins: [],
  corePlugins: require('tailwind-rn/unsupported-core-plugins'),
}
```

**Comment by naveen1337** [comment]
make sure the  JIT server is up and running,

**Comment by kotsh23** [comment]
jit server is not working fine
i have to stop it and run again to create the new json

**Comment by benjefferies** [comment]
@albertcito I had issues with this on 4.2.0 but reverting to 4.1.0 fixes this @vadimdemedes @catalinmiron

**Comment by erquhart** [comment]
Spent more time than I care to admit on this, but it turns out we're just forgetting to prefix `font-`, eg., `font-inter-light`. Which, to be fair, could be more explicitly called out in the tailwind css docs.

```
module.exports = {
  theme: {
    // extend is optional, works fine with or without
    extend: {
    fontFamily: {
      'sans': ['Arial'], // outputs "font-sans"
      'inter-light': ['Inter_300Light'], // outputs "font-inter-light"
    },
  },
}
```

Works fine in tailwind-rn 4.2.0, works with or without theme extension.

**Comment by tommoholmes** [comment]
Hi @erquhart I try to add tailwind.config.js like yours,
but I still got error like this
`Unrecognized font familly `
here my tailwind.config.js 

```
module.exports = {
  theme: {
    extend: {
      fontFamily: {
        'opensans': ['OpenSans-Regular'],
      }
    },
  },
  plugins: [],
  content: ['./_src/**/*.{js,jsx,ts,tsx}'],
  corePlugins: require('tailwind-rn/unsupported-core-plugins'),
}
```

and here my react-native.config.js

```
module.exports = {
    assets: ['./_src/assets/fonts'],
 };
```

**Comment by erquhart** [comment]
@tommoholmes can you share a code snippet where you’re actually using the font?
