### ISSUE TITLE
react native web

### ISSUE THREAD

**Issue by johhansantana** [vadimdemedes/tailwind-rn#161]
Has someone been able to use latest version with react-native-web? Specifically using Nextjs.

I keep getting `Cannot find module 'react-native'`. I think I remember being able to use previous versions without this problem.

**EDIT**
Yup, was able to use it with version 3.0.1 no prob.

**Comment by JeffAbneyTurn** [comment]
Thanks for this, after a few hours of google error messages, I just downgraded to 3.0.1 and solved the issue.

**Comment by juanpprieto** [comment]
Hi, any plans to support `react-native-web` on newer versions?

**Comment by vadimdemedes** [comment]
Hey folks, this package is only for React Native. There are no plans to support `react-native-web`, because there would be no way of detecting and stripping unsupported CSS properties for React Native.
