### ISSUE TITLE
Unsupported Tailwind class error

### ISSUE THREAD

**Issue by eminvergil** [vadimdemedes/tailwind-rn#167]
I followed the instructions but React Native gives Unsupported Tailwind class error in the console.

<img width="599" alt="Screen Shot 2022-05-02 at 18 21 30" src="https://user-images.githubusercontent.com/17277419/166263348-7ed9d4ee-3e02-4ed5-8f95-6d4a2186fc92.png">

App.js:

```javascript

import { Text, View } from "react-native";
import { StatusBar } from "expo-status-bar";
import utilities from "./tailwind.json";
import { TailwindProvider, useTailwind } from "tailwind-rn";
import React from "react";

export default function App() {
  return (
    <TailwindProvider utilities={utilities}>
      <SomePage />
    </TailwindProvider>
  );
}

function SomePage() {
  const tailwind = useTailwind();

  return (
    <View style={tailwind("bg-black flex flex-1 justify-center")}>
      <Text style={tailwind("text-3xl font-bold text-white")}>hello world</Text>
      <StatusBar style="auto" />
    </View>
  );
}
````

tailwind.config.js

```javascript
module.exports = {
  content: [],
  theme: {
    extend: {},
  },
  plugins: [],
  corePlugins: require('tailwind-rn/unsupported-core-plugins'),
}

```

tailwind.json

```javascript
{}
```

**Comment by jae1jeong** [comment]
same error too

**Comment by jae1jeong** [comment]
past this code in tailwind.config.js 
content: ['./src/**/*.{js,jsx,ts,tsx}'],
this worked for me

**Comment by jae1jeong** [comment]
@eminvergil have you tried `npm run` (dev:tailwind) while coding?

**Comment by panbak** [comment]
check your `tailwind.config.js` file. You may need to change `content: ['./src/**/*.{js,jsx,ts,tsx}']` to `content: ['./app/**/*.{js,jsx,ts,tsx}']`
depending on your project folder structure. That was the case for me.

**Comment by rieg-ec** [comment]
> check your `tailwind.config.js` file. You may need to change `content: ['./src/**/*.{js,jsx,ts,tsx}']` to `content: ['./app/**/*.{js,jsx,ts,tsx}']` depending on your project folder structure. That was the case for me.

this worked for me 👍 it was initally `content: []` after setting up tailwind-rn

**Comment by mnik01** [comment]
Thanks guys. It worked for me too. Changing the content in tailwind config

**Comment by eminvergil** [comment]
Hi, I'm closing this issue because everyone seems like solved this problem by changing the content in tailwind config.
