### ISSUE TITLE
How to run the watch command within a single terminal running react-native as well?

### ISSUE THREAD

**Issue by johhansantana** [vadimdemedes/tailwind-rn#173]
Hello

My question is since the command for watching for changes is meant to be run and leave running, I would like to know what workaround you use to simply run react native and the tailwind watcher at the same time or do you simply run it with 2 terminals apart?

I figured you could use `concurrently` but this blocks the terminal from being able to use the shortcuts for reloading the react native app by pressing `r` inside the terminal.

**Comment by vadimdemedes** [comment]
Yep, I use two terminal tabs for this.
