### ISSUE TITLE
How to use tailwind imports with react native- can tailwind be shortened to tw

### ISSUE THREAD

**Issue by Shange-Fagan** [vadimdemedes/tailwind-rn#178]
Hello everyone, I am following the youtube tutorial on how to create a tinder clone with react native and expo, at 20 minutes he proceeds to install tailwind and change the default app.js file with a simple import tw from "tailwind-rn"; I have copied the code word for word and yet I am getting the error "render error - TypeError: (0, _tailwindRn.default) is not a function. (In '(0, _tailwindRn.default)('flex-1 justify-center items-center')', '(0, _tailwindRn.default)' is undefined)" the onyl difference is that he has yarn lock on his project so he has used "yarn add tailwind-rn" whereas I used "npm install tailwind-rn" maybe the error is something to do with the computer thinking I dont have tailwind installed, but I do. What should I do? Many thanks. 
my code:
<img width="1279" alt="Screenshot 2022-07-11 at 19 07 00" src="https://user-images.githubusercontent.com/81960347/179756386-1995153d-cf0a-4e2e-a67d-5f266f9dd6dd.png">
their code:
https://youtu.be/qJaFIGjyRms
![IMG_8008](https://user-images.githubusercontent.com/81960347/179756670-532801eb-a170-47a9-8484-a91c507c7f97.png)

**Comment by vadimdemedes** [comment]
That video used an old `tailwind-rn` version. Use a migration guide to update from 2.x to 3.x → https://github.com/vadimdemedes/tailwind-rn/blob/master/migrate.md.
