### ISSUE TITLE
classnames for autocompletion problem

### ISSUE THREAD

**Issue by mkalayci35** [vadimdemedes/tailwind-rn#18]
<img width="471" alt="Screen Shot 2020-05-23 at 11 55 55" src="https://user-images.githubusercontent.com/38668796/82726375-5c1f6e00-9cec-11ea-86f6-bb5b35bf745a.png">

**Comment by vadimdemedes** [comment]
See https://github.com/vadimdemedes/tailwind-rn/issues/15.
