### ISSUE TITLE
pseudo selectors

### ISSUE THREAD

**Issue by mattapperson** [vadimdemedes/tailwind-rn#19]
Hey! I have been using tailwind-rn for a project recently and developed this pattern and thought I would socialize it to get some feedback.

The idea here is to introduce psudo-selectors to tailwind-rn. Due to not being able to hook in very well to RN apis, I pass in the needed data as a second arg, an object of string keys with bool values to toggle the selectors. It supports single and multiple selectors just like tailwind supports.

The downside of my first stab at this is it is all runtime calculated, and it will make it hard to tyle the utility classes. As a result, I am trying some other options, that said, I will say the DX of this has been, in my opinion, really nice for making components with tailwind.

for example:

```ts
const tailwindProps = {
    disabled: disabled || !onPress,
    fullWidth: fullWidth,
    primary: varient === "primary",
    secondary: varient === "secondary",
    hasText: !!text,
};

// then later in my component, styling with...

 tailwind( `
    primary:bg-indigo-500 
    primary:border-indigo-600 
    primary:disabled:bg-gray-500

    secondary:bg-gray-200 
    secondary:border-gray-400 
    secondary:disabled:bg-white 
    secondary:disabled:border-gray-500

    fullWidth:w-full
    hasText:py-4
    border items-center justify-center rounded-md flex-row`,
    tailwindProps
)

```

This is accomplished by composing my typescript function like so:
 
```ts
import { create } from 'tailwind-rn';
import styles from '../assets/tw-styles.json';
const { tailwind, getColor } = create(styles);

type Selectors = Partial<{
    focus: boolean,
    disabled: boolean
    sm: boolean
    md: boolean
    lg: boolean
    [selector: string]: boolean
}>

const t = (styles: string, selectors?: Selectors) => {

    const cleanStyles = styles.replace(/\s\s+/g, ' ').trim()
    return {
        ...(selectors ? mapFromStyles(cleanStyles, selectors) : tailwind(cleanStyles)),
    }
}

const mapFromStyles = (styles: string, selectors: Selectors) => {
    const classes = styles.split(' ');
    const usedClasses = classes.filter(c => {
        if (!c.includes(':')) return true

        const psudos = c.split(':').slice(0, -1) as Array<keyof Selectors>;
        return psudos.map(p => selectors[p]).filter(v => v).length >= psudos.length
    }).sort((a, b) => {
        // the more matched selectors, the more exact match, make it last so it overides the previos options
        return (a.split(":").length - 1) - (b.split(":").length - 1);
    }).map(c => c.split(':').pop()).join(' ');

    return tailwind(usedClasses)
}

export { t as tailwind, t, getColor, mapFromStyles };
```

**Comment by KULTI1995** [comment]
will you give tw-styles.json?
And how to use it, with "hover:"?

**Comment by mattapperson** [comment]
@KULTI1995 that's just the custom tailwind themes defined in the dock and nothing special and not required.

hover: would work by just doing something like:

```
tailwind('bg-white hover:bg-blue-300', { hover: state.hover })
```
In this case, you are maintaining the hover state, react native is not web and does not have component states built-in. But in this example, if state.hover === true then the bg displayed will be the `bg-blue-300`, and if false then it would use the `bg-white`.

**Comment by vadimdemedes** [comment]
Hey @mattapperson, I think a functionality like this would be out of scope of this module, as it's only about exposing Tailwind classes in a React Native-compatible way. Otherwise it's risking to become a CSS-in-React Native library.

Looking at your code, I think an abstraction like this one would make more sense:

```jsx
<Component style={apply({
  primary: tailwind('primary styles'),
  secondary: tailwind('secondary styles'),
  shared: tailwind('shared styles between the two')
})}/>
```

I think it also reminds me of [classnames](https://www.npmjs.com/package/classnames) module, perhaps you'd find it interesting too.

Thanks for sharing though!

**Comment by JEGardner** [comment]
@mattapperson I like the solution, thanks! Works nicely with [react-native-web-hooks](https://blog.expo.io/css-pseudo-class-effects-in-expo-for-web-56649f88eb6b). I'm using React Native Web, so hover and other pseudo-classes are required.

**Comment by Jakobo** [comment]
I took Matt's work and [put it into an npm module](https://github.com/Jakobo/tailwind-rn-gust) which offers not only the `tailwind(classNames, selectors)` syntax, but also includes a component generator & a react hook for the common pattern of translating react-native events like `pressIn`/`pressOut` into selectors that work with the new `tailwind` function.

The goal was to create a CSS-in-JS bridge on top of tailwind-rn with as little surface area as possible.

Pattern-wise, the result is closer to dotenv than classnames: taking the result of tailwind-rn's `create()` and adding additional functionality, while passing through to the original `tailwind` and `getColor` once the additional features are resolved.
