### ISSUE TITLE
Responsive not working

### ISSUE THREAD

**Issue by renege** [vadimdemedes/tailwind-rn#25]
Hi @vadimdemedes 

Nice package!

But the following is not working:
``<View style={tailwind('w-1/3 sm:w-full items-center')}>```

Expected that the react-native app on ```sm:``` was full width and otherwise 1/3'th width..

**Comment by vadimdemedes** [comment]
See readme, there's no support for responsive utilities at the moment. Also, classes like `sm`, `md` or `lg` are kind of meaningless in the mobile environment. I think classes like `portrait`, `landscape`, `iphone`, `ipad` would be more appropriate, but I honestly don't know yet, haven't thought about it.

Let me know if you have more thoughts on this though.
