### ISSUE TITLE
Using Plugins

### ISSUE THREAD

**Issue by vmarcel** [vadimdemedes/tailwind-rn#30]
Hello, first off great work on getting this on RN. 

I wanted to ask if plugins are considered when customizing using `npx create-tailwind-rn`? 
The reason I ask is because we are using a gradient plugin and noticed that the gradient utility classes aren't generated in the `style.json` file

Also last note. I noticed that anything set in the `extend` of tailwind config doesn't get pulled into the `styles.json` file

**Comment by vmarcel** [comment]
I figured out solving both issues. closing issue

**Comment by Faisal-Manzer** [comment]
Can you help how you resolved the issue? I am facing the same.

**Comment by keiranvv** [comment]
I'd also like to know how this was resolved please

**Comment by vmarcel** [comment]
So for the first issue. This library just can't do that. In the docs it provides what is customizable. So if you want a linear gradient for react native you have to download the `react-native-linear-gradient` library. No way around that. Sorry =(

The second issue was my placement of the `extend` object property. It needs to be a property of `theme` for this to work properly.
