### ISSUE TITLE
Support @apply

### ISSUE THREAD

**Issue by nahtnam** [vadimdemedes/tailwind-rn#32]
Hello,

I love the idea of this project! I was wondering if `@apply` is something this library can support? I am working on my own internal "css framework" which works something like this:

```
.button {
  @apply py-2 px-2 text-uppercase...
}

.button-blue {
  @apply bg-blue-500
}
```

I was wondering if this library could somehow ingest this kind of file and then convert `button` to its associated styles (and ignore whatever react native doesn't support)?

**Comment by vadimdemedes** [comment]
I think `tailwind()` function itself is an equivalent of `@apply` already. `@apply py-2 px-2 bg-blue-500` is the same as `tailwind('py-2 px-2 bg-blue-500')`.
