### ISSUE TITLE
Font Weight probleme with some props

### ISSUE THREAD

**Issue by josef256** [vadimdemedes/tailwind-rn#33]
Hello,
font Weight  semibold/thin/hairline don't seem to work, it render exactly the same. the doc don't mention any exception so they must be all supported, no ?

tested on Android.

**also any ETA whene box shadow will be supported ?**

**Comment by vadimdemedes** [comment]
Could you see if font weight works without `tailwind-rn`? Haven't tested this library on Android.

As for shadows, if I'm not mistaken it's a React Native issue, where they don't support spread shadow property, which Tailwind CSS specifies.
