### ISSUE TITLE
Tailwind UI usage

### ISSUE THREAD

**Issue by nandorojo** [vadimdemedes/tailwind-rn#35]
Hey, thanks for this awesome library. Out of curiosity, does this work with Tailwind UI? 

I'm new to the Tailwind ecosystem so I'm trying to understand how it all works together. I know that I'd have to change the Tailwind UI HTML to react native primitives, but assuming I did that, would it work?

**Comment by danjus10** [comment]
It would work in theory given tailwindUI is just template library of use cases for css- although the rn library supports a subset of the full tailwindcss so I’d say it’s not going to be perfect.

You’re better of using tailwind Ui as inspiration for UI in your tailwind-rn projects IMO

—
Get fluid.work and work a better day.
________________________________

**Comment by nandorojo** [comment]
Thanks for the quick reply. Makes sense to me.

For context, I'm working on [Dripsy](https://github.com/nandorojo/dripsy), a responsive design system for React Native / React Native Web. I've been wondering if there's a way to fit Tailwind in. The bottleneck to getting this library to fit into my responsive design API is that I use array styles for breakpoints.

Thanks again!

**Comment by danjus10** [comment]
Yeah I use array styles as well (if I know what you’re referring to)- the tailwind function can be chained into your existing styles .e.g

[{styles.something}, tailwind(‘Bg-blue-100’)]

Also you can set custom breakpoints in tailwind config for responsive boundaries if that’s needed.

—
Get fluid.work and work a better day.
________________________________

**Comment by nandorojo** [comment]
I actually mean array styles like this:

```jsx
<Text
  sx={{
    fontSize: [14, 16, 20], // 14 on mobile, 16 on tablet, 20 on desktop
    color: ['primary', null, 'accent'], // `primary` on mobile & tablet, `accent` on desktop
  }}
>
  Responsive font size?? 🤯
</Text>
```

The value in each array item shows for that breakpoint. Since RN doesn't have breakpoints, I've made a custom workaround that works with server side rendering too.

**Comment by danjus10** [comment]
Check out tailwind convention of sm:text-xl md:text-2xl lg:text-3xl    (For example)

Similar concept but tw is more verbose in syntax

—
Get fluid.work and work a better day.
________________________________
