### ISSUE TITLE
Using new tailwind with some better stuff

### ISSUE THREAD

**Issue by infothien** [vadimdemedes/tailwind-rn#36]
Hi there, first of all thank you for this lib, it is really convenient for people who like to use tailwind like me.

For new tailwind version, I really missed some feature like https://tailwindcss.com/docs/space#app, which is very save a lot of unessential codes to add margin between components in flex.

So do you guys have plan to update new version of tailwind for this package.

**Comment by vadimdemedes** [comment]
Hey @infothien, thanks!

Unfortunately, `space-*` classes can't be supported in React Native, because they use nested CSS selectors like `.space-y-0 > * + *`. `tailwind()` function exposed by this module basically returns an object of styles and doesn't have a concept of selectors.
