### ISSUE TITLE
npm registry not found

### ISSUE THREAD

**Issue by MaganAnkur** [vadimdemedes/tailwind-rn#38]
![Screen Shot 2020-09-28 at 11 58 54 PM](https://user-images.githubusercontent.com/42070594/94511175-9ba01e80-01e6-11eb-9e29-8d41feeb2754.png)

Can anybody please help why am I getting above error after running npx create-tailwind-rn

**Comment by vadimdemedes** [comment]
`create-tailwind-rn` is not a standalone package, this CLI is part of `tailwind-rn` package. Install `tailwind-rn`, then try again.
