### ISSUE TITLE
Update Tailwind CSS to latest version

### ISSUE THREAD

**Issue by josef256** [vadimdemedes/tailwind-rn#39]
the library is currently using tailwind 1.2.0 (**current version is 1.8.7**), will the tailwind version be updated ?

**Comment by vadimdemedes** [comment]
Updated to Tailwind CSS v1.8.10 in master, will release soon.

**Comment by vadimdemedes** [comment]
Released in [2.0.0](https://github.com/vadimdemedes/tailwind-rn/releases/tag/v2.0.0).
