### ISSUE TITLE
[Proposal] create production and development version

### ISSUE THREAD

**Issue by ecreeth** [vadimdemedes/tailwind-rn#4]
My proposal is to separate `tailwind-rn` into two versions:

#### Development
This version will allow us to give error messages and warnings.

#### Production
While the production version will remain only with the business logic.

An example of this is the following code; which is unnecessary in the production version.
```diff
const tailwind = classNames => {
const obj = {};

	for (const className of classNames.split(' ')) {
-          if (styles[className]) {
		Object.assign(obj, styles[className]);
-           } else {
-                 console.warn(`Unsupported Tailwind class: "${className}"`);
-          }
	}

	return obj;
};
```

😄 I know it's a small package and maybe I'm exaggerating a bit. We will have to do a few benchmarks!

**Comment by vadimdemedes** [comment]
What's the harm in leaving `console.warn()`?
