### ISSUE TITLE
Controlling File Size tailwind-rn

### ISSUE THREAD

**Issue by nurulakbaral** [vadimdemedes/tailwind-rn#42]
How do I control the file size of Tailwind CSS in React Native?

**Comment by vadimdemedes** [comment]
After https://github.com/vadimdemedes/tailwind-rn/pull/43 is merged, you can customize your Tailwind config to exclude properties you're not using. See https://tailwindcss.com/docs/controlling-file-size#disabling-unused-utilities-and-variants for how to do it.
