### ISSUE TITLE
Using numerous libraries that are deprecated or outright broken

### ISSUE THREAD

**Issue by OrganicCat** [vadimdemedes/tailwind-rn#44]
Hey, I noticed when installing that there were numerous libraries you're using that are unsupported, deprecated, and in some cases simply will not work on newer versions of node or when combined with other newer libraries.

Now I usually see a few deprecated, that's just a given, but there's probably a dozen here and some of the libraries are screaming "Don't use me! I will break your program!"

Suggested updating at least the most severe dependency issues

**Comment by vadimdemedes** [comment]
Which libraries exactly?
