### ISSUE TITLE
Font family

### ISSUE THREAD

**Issue by javierdac** [vadimdemedes/tailwind-rn#45]
is it possible to add font family like here: https://tailwindcss.com/docs/font-family?

**Comment by sanojsilva** [comment]
@javierdac I don't think font-family supports with tailwind-rn since they don't specify in docs. But you could do that with a custom config file.

**Comment by javierdac** [comment]
@sanojsilva Thank you very much for your answer. How do i do that with a custom file?

**Comment by sanojsilva** [comment]
As per this settings you can customize the configuration.
https://github.com/vadimdemedes/tailwind-rn#customization

Once you've done that you can add a there will be following files.
- tailwind.config.js
- styles.json
- tailwind.js

Then you have to create a json file (I have named it as extra-styles.json) with your font configurations similar to below format.
```json
{
	"font-kotori-bold": {
            "fontFamily": "kotori-bold"
	},
	"font-kotori": {
            "fontFamily": "kotori"
	}
}
```
After that in tailwind.js file import the extra-styles.json file and upate like below.
```js
import { create } from "tailwind-rn";
import extraStyles from "./extra-styles.json";
import styles from "./styles.json";

const { tailwind, getColor } = create({ ...styles, ...extraStyles });
export { tailwind, getColor };
```
Then use that class like below in react native code.
```jsx
   <Text style={tailwind("font-kotori-bold")}>
      Login
    </Text>
```

**Comment by andres-j** [comment]
Hi @sanojsilva Thanks for the great step by step. I am trying to understand how this works a little better and missing one thing in your above answer: Where is the actual font file coming into play?


I see that you add styles to styles.json via extra-styles:
```
{
	"font-kotori-bold": {
            "fontFamily": "kotori-bold"
	},
	"font-kotori": {
            "fontFamily": "kotori"
	}
}
```

which in turn must reference a custom font family in tailwind.config.js:

```
module.exports = {
  theme: {
    extend: {
      fontFamily: {
        sans: ["kotori"]
      },
```

How does the font file become available to tailwind.config.js (or anywhere else) exactly? Where should I be placing and loading it?

**Comment by andres-j** [comment]
Hi All - here to answer my own question. I am using react native, typescript and expo and was able to load custom fonts. There are a few gotchas that can cause problems. Here is what I did:

1. Add your font file to your app. I have mine in `/assets/fonts `
2. Follow the instructions [here](https://github.com/vadimdemedes/tailwind-rn#customization) - go through the motions to get the files that @sanojsilva mentions created: tailwind.config.js, styles.json and tailwind.js. You do **not** have to modify tailwind.config.js 
3. In your main app file (App.tsx for me) load the fonts into your app. In expo they provide a `useFonts` hook:
![image](https://user-images.githubusercontent.com/17058214/106950840-fa2d5a00-66fc-11eb-8b99-a5f936103adf.png)
Note the names you use (plexRegular, plexMedium, plexSemiBold for me)
4. Create a font-styles.json file and add the classes. Use the names from step 3 for `fontFamily`. So mine looks like: 
![image](https://user-images.githubusercontent.com/17058214/106951241-850e5480-66fd-11eb-8498-3d66342e739d.png) and I would add the style to an element via `tailwind('font-plex-regular')`
5. Open tailwind.js and modify it exactly like @sanojsilva shows using the name of the file you created in step 4 (for me, font-styles.json)

And thats it! You should be able to style a text component by adding your font classes. Be sure to specify **your** tailwind.js when you import the class to use in other components ie `import {tailwind} from '../path/to/tailwind.js'` or you won't see any of your custom classes.

**Comment by vadimdemedes** [comment]
Thanks for posting your findings, @andres-j!

**Comment by erquhart** [comment]
Update for tailwind-rn 4.x+, configure custom font families in `tailwind.config.js`, example below.

**Note:** Tailwind will output the class names with a `font-` prefix, Eg., the first font family below is output as `font-primary-100`.

```js
module.exports = {
  content: ['src/**/*.js'],
  theme: {
    extend: {
      fontFamily: {
        'primary-100': ['Inter_100Thin'],
        'primary-200': ['Inter_200ExtraLight'],
        'primary-300': ['Inter_300Light'],
        'primary-400': ['Inter_400Regular'],
        'primary-500': ['Inter_500Medium'],
        'primary-600': ['Inter_600SemiBold'],
        'primary-700': ['Inter_700Bold'],
        'primary-800': ['Inter_800ExtraBold'],
        'primary-900': ['Inter_900Black'],
      },
    },
  },
  plugins: [],
  corePlugins: require('tailwind-rn/unsupported-core-plugins'),
}
```
