### ISSUE TITLE
tailwindcss 2.0 requires postcss 8 and tailwind-rn is using postcss 7

### ISSUE THREAD

**Issue by oussamabouchareb** [vadimdemedes/tailwind-rn#49]
everytime I try to use ```npx creaate-tailwind-rn``` I get this error:
```
/node_modules/tailwind-rn/node_modules/postcss/lib/processor.js:153
        throw new Error('PostCSS plugin ' + plugin.postcssPlugin + ' requires PostCSS 8.\n' + 'Migration guide for end-users:\n' + 'https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users');
        ^

Error: PostCSS plugin tailwindcss requires PostCSS 8.
```

**Comment by oussamabouchareb** [comment]
in case someone has the same issue you can solve this by using tailwind compatibility build:
``` 
yarn remove tailwindcss 
yarn add -D tailwindcss@npm:@tailwindcss/postcss7-compat
```

**Comment by mkalayci35** [comment]
me problem ```Cannot find module 'autoprefixer'```

**Comment by aswinmohanme** [comment]
A temporary fix would  be to use `npx tailwindcss@1.9.6 init` and use the  older version

**Comment by oussamabouchareb** [comment]
if any maintainer is looking at this please consider pull request #48

**Comment by sahildeliwala** [comment]
This worked for me:
`yarn add tailwindcss@npm:@tailwindcss/postcss7-compat postcss@^7 autoprefixer@^9`

**Comment by aswinmohanme** [comment]
This has been fixed in the new `tailwind-rn` version

**Comment by vadimdemedes** [comment]
@aswinmohanme is right, it's no longer an issue in `3.0.0`.
