### ISSUE TITLE
[Question] How to use shadows?

### ISSUE THREAD

**Issue by ospfranco** [vadimdemedes/tailwind-rn#52]
Hey! Thanks a lot for the awesome package! I was just migrating my app to it, but I've run into some problem with shadows, when trying to use the class apparently it is not supported, is there any way to use it?

**Comment by adscud** [comment]
@ospfranco I think you have to use the react-native shadows, cause `box-shadow` isn't supported by react native

**Comment by vadimdemedes** [comment]
Not right now, last time I checked React Native didn't expose enough parameters for configuring the shadow like CSS does.
