### ISSUE TITLE
Module Resolution Error when importing in an Expo project

### ISSUE THREAD

**Issue by drixie** [vadimdemedes/tailwind-rn#53]
I got this error just by importing tailwind-rn: 

Internal Error Metro has encountered an error: While trying to resolve module `tailwind-rn` from file `App.js`, the package `node_modules/tailwind-rn/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`node_modules/tailwind-rn/index`

**Comment by drixie** [comment]
This error comes up when I try to run the project in the iOS simulator. 

It gives not error when I the packager runs it on the web, however color-based styles do not work, while other styles do

**Comment by drixie** [comment]
Never mind. I just restarted everything and it works now.

**Comment by Teklit17** [comment]
how do you restarted
