### ISSUE TITLE
npx tailwindcss init throwing Cannot find module 'autoprefixer'

### ISSUE THREAD

**Issue by sandro-salles** [vadimdemedes/tailwind-rn#54]
I'm using version 3.0.0 ... 
Node v14.15.3

When i try to run 
npx tailwindcss init

It throws **Cannot find module 'autoprefixer'**

When i try to run npx create-tailwind-rn, it throws  **Cannot find module 'tailwindcss'** ..

Can you guys help me?

**Comment by adscud** [comment]
@sandro-salles Hi Sandro, with `npx tailwindcss-cli@latest init -p` it works. 
See https://github.com/tailwindlabs/tailwindcss/issues/2957

**Comment by adscud** [comment]
@sandro-salles `npm install tailwindcss@latest postcss@latest autoprefixer@latest`

**Comment by vstlouis** [comment]
> @sandro-salles `npm install tailwindcss@latest postcss@latest autoprefixer@latest`

Merci broski. I was missing the tailwindcss@latest

**Comment by vadimdemedes** [comment]
See https://tailwindcss.com/docs/installation#install-tailwind-via-npm for up-to-date installation instructions for Tailwind. This module is just a wrapper around it.
