### ISSUE TITLE
Background steps not working

### ISSUE THREAD

**Issue by Ethan-Hill** [vadimdemedes/tailwind-rn#57]
`style={tailwind(
        "flex flex-col justify-center items-center bg-gradient-to-r from-purple-400 via-pink-500 to-red-500 min-h-full w-full "
      )}`
      
    I get all the different bg gradient classes as an unsupported warning, any ideas?

**Comment by mike-roberts** [comment]
CSS background images & therefore gradients are not supported in React Native.
