### ISSUE TITLE
Border radius issues

### ISSUE THREAD

**Issue by MaxEvan** [vadimdemedes/tailwind-rn#58]
When I use `rounded-lg` for example I expect my button to have all 4 rounded corners on iOS and Android but since it's translated to this:

```
...
  "rounded-lg": {
    "borderTopLeftRadius": 8,
    "borderTopRightRadius": 8,
    "borderBottomRightRadius": 8,
    "borderBottomLeftRadius": 8
  }
...
```

I think that since the specific corner radius is not well supported on iOS, there is a problem with translating it to that when you are applying the same border radius to all corners.

**Comment by jsbls** [comment]
Hey Max. I'm using `rounded` all over my iOS app without any issues. What problem are you facing? I've had some instances of `rounded` not displaying, but when that happens I usually just wrap the element inside a `View` parent tag, and add `rounded-lg overflow-hidden` to it and that gets it done. ie:

```
<View style={tailwind("overflow-hidden rounded-lg")}>
  <View style={tailwind("bg-blue-800")}>
    <Text>...</Text>
  </View>
</View>
```

**Comment by wouterds** [comment]
Indeed doesn't work on Text but does work on View.
