### ISSUE TITLE
Font Weight with custom font

### ISSUE THREAD

**Issue by Gregoirevda** [vadimdemedes/tailwind-rn#59]
On Android, not all phones come with the Roboto font, so there's a need to install the Roboto font with several weights.
eg: Roboto thin, Roboto bold

The font needs to be referenced in the fontFamilly, eg 
```js
{
  text: {  fontFamily: 'Roboto Medium'},
  boldText: {fontFamily: 'Roboto Bold'}
}
``` 

I don't think there's a way to have a generic Text component eg
```js
function Txt({children}) {
  return <Text style={Platform.select({android: {fontFamily: 'Roboto'})}>{children}</Text>
}
```

and then use tailwindcss weight:
```js
function App() {
  return <Txt style={tw('font-bold')}>Hello World</Txt>
}
```

As the weight needs to be referenced in the fontFamily directly

**Comment by vadimdemedes** [comment]
Check out how other people solved the problem of adding custom fonts - https://github.com/vadimdemedes/tailwind-rn/issues/45.
