### ISSUE TITLE
Unsupported Tailwind Class for colors / getColor

### ISSUE THREAD

**Issue by andres-j** [vadimdemedes/tailwind-rn#60]
Hello,

I've been testing out this library and running into one peculiar issue. 

I have defined a custom tailwind config and `npx create-tailwind-rn` creates a styles.json without complaint. Within the styles json I see that all the derived component color classes (bg-red-100, text-green-200 etc) based off my custom colors are created but the actual color classes I would use with getColor (eg `getColor('green-200'))`) do not appear. When I try to use `getColor` the app warns "unsupported tailwind class" for any color I try. Am I missing something to get the color classes showing in styles/ callable via getColor?

Thanks in advance for any help!

**Comment by jsbls** [comment]
Dumb question but have you tried restarting `expo-cli` and/or clearing the cache? I've had this happen a few times and it usually gets fixed with this. Can you see said classes in `styles.json` after running `npx create-tailwind-rn`?

**Comment by andres-j** [comment]
This was my fault. I was doing everything correctly except I was still importing tailwind from the base 'tailwind-rn' in my script whereas I should have imported from the script I created (tailwind.tsx).
