### ISSUE TITLE
[Question] How to use focus, hover and other states?

### ISSUE THREAD

**Issue by jachicas** [vadimdemedes/tailwind-rn#63]
When i use this, i have an error: Unsupported tailwind class 
![image](https://user-images.githubusercontent.com/54284229/106949230-4fb03980-66f2-11eb-95dd-853d428c9e9b.png)

**Comment by vadimdemedes** [comment]
There are no focus or hover states in React Native. You'd have to detect focus on the view yourself and apply different styles via `tailwind` function.
