### ISSUE TITLE
npx create-tailwind-rn throwing 404 error

### ISSUE THREAD

**Issue by hcphoon01** [vadimdemedes/tailwind-rn#65]
I've installed tailwind-rn and I'm trying to create the styles.json file using `npx create-tailwind-rn` but I get this error 
```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/create-tailwind-rn - Not found
npm ERR! 404 
npm ERR! 404  'create-tailwind-rn@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)  
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by dennisbouwpas** [comment]
+1

**Comment by sveisvei** [comment]
The binary is named via `package.json`: https://github.com/vadimdemedes/tailwind-rn/blob/master/package.json#L13.

Using npx based on docs `npx -p=tailwind-rn create-tailwind-rn` still fails with:

```
npx: installed 79 in 4.619s
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'tailwindcss'
Require stack:
- /.npm/_npx/43168/lib/node_modules/tailwind-rn/cli.js
```

**Comment by realmichaelye** [comment]
+1

**Comment by adscud** [comment]
> The binary is named via `package.json`: https://github.com/vadimdemedes/tailwind-rn/blob/master/package.json#L13.
> 
> Using npx based on docs `npx -p=tailwind-rn create-tailwind-rn` still fails with:
> 
> ```
> npx: installed 79 in 4.619s
> internal/modules/cjs/loader.js:883
>   throw err;
>   ^
> 
> Error: Cannot find module 'tailwindcss'
> Require stack:
> - /.npm/_npx/43168/lib/node_modules/tailwind-rn/cli.js
> ```

`npm install tailwindcss@latest postcss@latest autoprefixer@latest`

**Comment by sveisvei** [comment]
@adscud Kinda breaks the assumption of how `npx` usually is used - but sure, being explicit that it should be local in the given package it would maybe work better. A dependency check in the cli might help resolve this usability issue.

**Comment by adscud** [comment]
@sveisvei Agreed with you. I've also loose lot of time to understand why I've this error, it was logic for me that Tailwind is already include inside the package.

**Comment by GTSConserve** [comment]
+1

**Comment by chinieer** [comment]
any solution?

**Comment by adscud** [comment]
@chinieer look above I have provided the solution.

**Comment by Irenimoyan** [comment]
npx tailwindcss init -p
npm error could not determine executable to run
npm error A complete log of this run can be found in: C:\Users\sheut\AppData\Local\npm-cache\_logs\2025-08-11T13_38_20_121Z-debug-0.log 


What could be wrong and why is it returning error when i hit the command npx tailwindcss init -p and how can i fix it please
