### ISSUE TITLE
Don't have elevation class

### ISSUE THREAD

**Issue by henriquebarrosx** [vadimdemedes/tailwind-rn#66]
Tailwind-rn don't have support to elevation or shadow used in Tailwind

![image](https://user-images.githubusercontent.com/48387142/108144527-a6c9ed00-70a8-11eb-9383-29fd5d677988.png)

**Comment by GTSConserve** [comment]
If you want to use an elevation in android add elevation prop like `elevation={4}` 

Reference from React Native documentation: 
[https://reactnative.dev/docs/view-style-props#elevation](https://reactnative.dev/docs/view-style-props#elevation)

**Comment by henriquebarrosx** [comment]
> If you want to use an elevation in android add elevation prop like `elevation={4}`
> 
> Reference from React Native documentation:
> https://reactnative.dev/docs/view-style-props#elevation

Yeah, I know that.
But I think that also could be a good idea to insert an elevation style property inside **tailwind-rn**. It's an awesome library with a focus on the React Native style. Embracing this and other causes could further encourage the use of this library. What do you think?

**Comment by Sanan4li** [comment]
> > If you want to use an elevation in android add elevation prop like `elevation={4}`
> > Reference from React Native documentation:
> > https://reactnative.dev/docs/view-style-props#elevation
> 
> Yeah, I know that.
> But I think that also could be a good idea to insert an elevation style property inside **tailwind-rn**. It's an awesome library with a focus on the React Native style. Embracing this and other causes could further encourage the use of this library. What do you think?

I think it's an open-source library. If you can't find anything in the library, be a contributor. This is what open-source is all about.

**Comment by henriquebarrosx** [comment]
> Just to add some clarity on the issue. `tailwind-rn` is specifically focused on generating the `style` property. In order to support `elevation`, we'd probably need to return a nested object and then spread the result into the component itself which would be a breaking change for a lot of folks.
> 
> ```js
> const tailwindresults = { // from a tailwind() call
>   elevation: X,
>   style: {
>     // styles
>   }
> }
> 
> // later on...
> <View {...tailwindresults} />
> ```
> 
> # Workaround (userland code)
> Since that's not really a change we can make without changing the purpose of `tailwind-rn`, we can write a local wrapper function that gives us this behavior. You might need to further adapt this to your use case.
> 
> ```js
> import { create } from "tailwind-rn";
> 
> const {tailwind: ogTailwind} = create({/*styles*/});
> 
> export const tailwind = (str) => {
>   const props = {}; // contains all props we precompute
> 
>   // strip elevation out of our string and turn it into a react native prop
>   str = str.replace(/elevation-([\d]+)/g, (match, elev) => {
>     props.elevation = parseInt(elev, 10);
> 	return str.replace(match, "");
>   });
> 
>   return {
>     // add all props, merged with the tailwind result
>     // if you'd like to support shadows on a single elevation-N prop
>     // you might need a library like deepmerge here
>     ...props,
>     ...tailwind(str)
>   };
> }
> ```

I did exactly the first thing that you said: imbuting de elevation class and use the spread opereator to merge with the other elements. I will follow the @Sanan4li suggestion and try to colabore on project. I just need time to do this rsrsrs

**Comment by vadimdemedes** [comment]
`tailwind-rn`'s goal is to match the utilities (styles) provided by Tailwind CSS, that's why I don't think it's a good idea to start adding custom ones on top of it. I think you could try adding a [custom utility](https://tailwindcss.com/docs/adding-custom-styles) for this, but I'm not sure if `tailwind-rn` can handle a non-standard rule like `elevation`. Worth a shot though, but make sure to use latest `4.0.0` version of `tailwind-rn`.
