### ISSUE TITLE
Length values under 1

### ISSUE THREAD

**Issue by fostimus** [vadimdemedes/tailwind-rn#67]
Values like m-0.5, h-0.5, etc. don't work, although they are supported in Tailwind.

**Comment by jakobo** [comment]
I just tried this here, and it seems to be working: https://runkit.com/jakobo/6109ec6cb9e461001bb84556

Do you mind sharing your `tailwind.config.js`? It's possible there's units such as `em` which the css-to-react-native library isn't translating correctly.
