### ISSUE TITLE
Support Tailwind 3.x with JIT

### ISSUE THREAD

**Issue by andrei-zgirvaci** [vadimdemedes/tailwind-rn#71]
Would be really cool to support some of the features presented in this video once it gets released 😊

https://www.youtube.com/watch?v=3O_3X7InOw8

**Comment by pheuter** [comment]
It works practically out of the box, just need the fix in #73 to support arbitrary values.

**Comment by andrei-zgirvaci** [comment]
Nice, thank you!

**Comment by baiqunicui** [comment]
any update for this feature?

**Comment by max-frai** [comment]
We need this pull request, please.

**Comment by vadimdemedes** [comment]
Working on a major new release with native support for JIT right now in `v4` branch. Coming soon!

**Comment by pvinis** [comment]
cool! I actually made it work locally, not to bad, and I'm loving the smaller json file.

**Comment by pvinis** [comment]
if you were not working on it I would make a PR probably. im trying to do a Babel plugin for a tw prop too but still WIP.

**Comment by vadimdemedes** [comment]
Hey folks, support for Tailwind 3.0 is now released in [v4.0.0](https://github.com/vadimdemedes/tailwind-rn/releases/tag/v4.0.0)!
