### ISSUE TITLE
Unsupported Tailwind class: 'fill-current'

### ISSUE THREAD

**Issue by finction** [vadimdemedes/tailwind-rn#74]
Noticed that the utility 'fill-current' thats used to color SVGs is not supported in tailwind-rn. You should probably add a note of it in the project's readme as it makes coloring SVGs very diffcult.

Are there any plans for adding this utility to tailwind-rn?

Any ideas of a work around for now? How can I give a fill color to an SVG if I cant use fill-current with text-*color*?

**Comment by jakobo** [comment]
As a workaround, you should be able to manually assign the fill style:

```
style={[
  tailwind(/* str with text color defined */),
  {
    fill: "currentColor"
  }
]}
```

**Comment by vadimdemedes** [comment]
It's now supported in the new [v4.0.0](https://github.com/vadimdemedes/tailwind-rn/releases/tag/v4.0.0) release!

**Comment by mcmillion** [comment]
I'm on 4.2.0 and 'fill-current' still says it's an unsupported class

**Comment by vadimdemedes** [comment]
I made a mistake there, it's not supported, because it doesn't exist in `View`'s or `Text`'s `style` objects.
