### ISSUE TITLE
Pressable with tailwind

### ISSUE THREAD

**Issue by willparsons** [vadimdemedes/tailwind-rn#75]
Is there any way to get tailwind to work within a pressable when you are using `pressed` like this? It just doesn't seem to recognize the function anymore.

```tsx
<Pressable
    style={({ pressed }) => [
        {
            backgroundColor: pressed
                ? getColor("blue-300")
                : getColor("blue-400"),
        },
        tailwind("w-10 h-full"),
    ]}
>
```

**Comment by Malthehave** [comment]
The above code works fine for me :)

**Comment by willparsons** [comment]
@Malthehave Sorry, I mean't I wanted to replace the need for the getColor and just have them replaced with something like `tailwind("bg-blue-300") ? pressed : tailwind("bg-blue-400")`

**Comment by Malthehave** [comment]
I see. For that case you just have to switch the `pressed` and `tailwind("bg-blue-300")`
This would work:
`<Pressable style={pressed => pressed ? tailwind("bg-blue-300") : tailwind("bg-blue-400")}> ...`
