### ISSUE TITLE
About purge function

### ISSUE THREAD

**Issue by ekkoqin** [vadimdemedes/tailwind-rn#76]
I have set the file path in purge section in tailwind.config.js, but it seems not working.
So, is it possible to use purge function to reduce the bundle size in tailwind-rn?

**Comment by mstroiu** [comment]
Have you tried enabling it manually? https://tailwindcss.com/docs/optimizing-for-production#enabling-manually

`// tailwind.config.js
purge: {
enabled: true,
content: ['./src/**/*.vue'],
},`

**Comment by ekkoqin** [comment]
> Have you tried enabling it manually? https://tailwindcss.com/docs/optimizing-for-production#enabling-manually
> 
> `// tailwind.config.js purge: { enabled: true, content: ['./src/**/*.vue'], },`

Thanks, that is the answer to my question : )
