### ISSUE TITLE
Using any tracking property on android causes the app to close without an error

### ISSUE THREAD

**Issue by Ankcorn** [vadimdemedes/tailwind-rn#8]
Using the tracking class on android (SDK version 28) causes the app to close without error, I imagine it could be because letter spacing only supports numeric values but in the styles.json file the value is an em

If I could see how the styles.json was generated I'd be happy to submit a PR to fix

Really enjoying using this lib so far thanks!

**Comment by Ankcorn** [comment]
![image](https://user-images.githubusercontent.com/7361428/77846829-bb5f7700-71b0-11ea-8990-c0db6bd96f0d.png)
crashed with a message today, hope this helps 👍

**Comment by vadimdemedes** [comment]
Fixed in `1.0.1`, thanks for reporting!
