### ISSUE TITLE
Warnings when running create-tailwind-rn

### ISSUE THREAD

**Issue by joshuajung** [vadimdemedes/tailwind-rn#89]
This is an incredibly good tool – thank you! Everything works perfectly fine, but I'm seeing these logs when running `create-tailwind-rn` on 3.0.1 with TailwindCSS 2.2.4: 

```bash
> yarn create-tailwind-rn
yarn run v1.22.5
$ /(redacted)/node_modules/.bin/create-tailwind-rn
Expected style "--tw-backdrop-opacity: var(--tw-empty, )" to be unitless
Expected style "--tw-backdrop-opacity: opacity(0)" to be unitless
Expected style "--tw-backdrop-opacity: opacity(0.05)" to be unitless
Expected style "--tw-backdrop-opacity: opacity(0.1)" to be unitless
Expected style "--tw-backdrop-opacity: opacity(0.2)" to be unitless
Expected style "--tw-backdrop-opacity: opacity(0.25)" to be unitless
Expected style "--tw-backdrop-opacity: opacity(0.3)" to be unitless
Expected style "--tw-backdrop-opacity: opacity(0.4)" to be unitless
Expected style "--tw-backdrop-opacity: opacity(0.5)" to be unitless
Expected style "--tw-backdrop-opacity: opacity(0.6)" to be unitless
Expected style "--tw-backdrop-opacity: opacity(0.7)" to be unitless
Expected style "--tw-backdrop-opacity: opacity(0.75)" to be unitless
Expected style "--tw-backdrop-opacity: opacity(0.8)" to be unitless
Expected style "--tw-backdrop-opacity: opacity(0.9)" to be unitless
Expected style "--tw-backdrop-opacity: opacity(0.95)" to be unitless
Expected style "--tw-backdrop-opacity: opacity(1)" to be unitless
```

Not sure if this is something you want to have a look at, but I still wanted to leave a report.

**Comment by buitrbao222** [comment]
Got the same warnings after i install postcss and run `npx create-tailwind-rn`

**Comment by jakobo** [comment]
Can you try disabling the backdrop opacity in your tailwind config? https://tailwindcss.com/docs/backdrop-opacity#disabling as a workaround?

The error appears to be upstream in the css-to-react-native library: https://github.com/styled-components/css-to-react-native/blob/4f96cf6bb81b48894b53bce041512d495de715ba/src/index.js#L24

**Comment by Livijn** [comment]
> Can you try disabling the backdrop opacity in your tailwind config? https://tailwindcss.com/docs/backdrop-opacity#disabling as a workaround?
> 
> The error appears to be upstream in the css-to-react-native library: https://github.com/styled-components/css-to-react-native/blob/4f96cf6bb81b48894b53bce041512d495de715ba/src/index.js#L24

I had the same warnings and this reduces the warnings to a single: 
> Expected style "--tw-backdrop-opacity: var(--tw-empty, )" to be unitless

**Comment by vadimdemedes** [comment]
Hey folks, could you try the latest [v4.0.0](https://github.com/vadimdemedes/tailwind-rn/releases/tag/v4.0.0) release and see if it works for you? It's much more powerful yet simpler too than the old 3.x release.
