### ISSUE TITLE
Tailwind config

### ISSUE THREAD

**Issue by branislaav** [vadimdemedes/tailwind-rn#9]
Is it possible to use tailwind config?
eg: to create custom color palette?

**Comment by branislaav** [comment]
For anyone wondering, how to use this package with a custom color palette. You can either fork this package and change colors or you can use a package called [patch-package](https://www.npmjs.com/package/patch-package) and change generated styles in styles.json and still have an original package installed, it is not as convenient as having tailwind config but it works.

**Comment by netdesignr** [comment]
@vadimdemedes any intention to allow for Tailwind config? having the ability to extend the theme is quite crucial for custom projects. 
@branislaav thanks for the suggestions but I personally don't feel like this could be a good work around for an app in production.

@vadimdemedes thank you very much for building this for us!

**Comment by vadimdemedes** [comment]
Released in `1.1.0`, check out https://github.com/vadimdemedes/tailwind-rn#customization :)
