### ISSUE TITLE
Accept font-family property

### ISSUE THREAD

**Issue by ayloncarrijo** [vadimdemedes/tailwind-rn#95]
In tailwind.config.js, I want to implement the following component but I can't because "font-family" is ignored

```
plugins: [
    plugin(function ({ addComponents }) {
      addComponents({
        h1: {
          fontFamily: 'Roboto_300Light',
          fontStyle: 'normal',
          fontWeight: '300',
          fontSize: 96,
          lineHeight: '7rem',
          letterSpacing: -1.5,
        },
      });
    }),
]
```

**Comment by buitrbao222** [comment]
You can create your own custom styles object and pass it in the `create` function.
For example:
```javascript
import generatedStyles from 'styles.json';

const customStyles = {
  h1: {
    fontFamily: 'Roboto_300Light',
    fontStyle: 'normal',
    fontWeight: '300',
    fontSize: 96,
    lineHeight: '7rem',
    letterSpacing: -1.5,
  },
};

const { tailwind, getColor } = create({ ...generatedStyles, ...customStyles });

export { tailwind, getColor };
```
Now `tailwind('h1')` will work.

However, classes in `customStyles` won't be suggested by the TailwindCSS Intellisense plugin because the plugin uses your `tailwind.config.js` file for suggestions.

**Comment by vadimdemedes** [comment]
I just released [v4.0.0](https://github.com/vadimdemedes/tailwind-rn/releases/tag/v4.0.0), which includes built in support for custom font families. You can add your own fonts like this → https://tailwindcss.com/docs/font-family#customizing-your-theme. Once you do that (make sure there's only one font specified per utility), `tailwind-rn` automatically picks it up.

**Comment by camillo18tre** [comment]
@vadimdemedes what are the steps to import a custom font?, I mean, I've my custom fonts into: ./assets/fonts/my-font.ttf , so how can I import into the project before to validate It into tailwind.config.js?

thank you

**Comment by kelvinndmo** [comment]
@camillo18tre  did you find a solution for this cc @vadimdemedes

**Comment by vadimdemedes** [comment]
There seems to be plenty of tutorials about this, here's one for example → https://dev.to/aneeqakhan/add-custom-fonts-in-react-native-0-63-for-ios-and-android-3a9e.
