### ISSUE TITLE
Add platform prefixes

### ISSUE THREAD

**Issue by sudoaugustin** [vadimdemedes/tailwind-rn#99]
It would be nice to have some platform prefixes like tailwind( "android:bg-blue-400 ios:bg-green-400");

**Comment by vadimdemedes** [comment]
What's the use case for having this feature? Would you want a different color (or other parts of UI) depending on the platform? If so, why?

**Comment by cupliz** [comment]
for example, we want ios app to have in-app navigation but hidden in android app.

**Comment by vadimdemedes** [comment]
I think it'd be better to not render the component for it at all, rather than only hide it visually.

**Comment by vadimdemedes** [comment]
Going to close this one, until there's a better use case.

**Comment by kneza23** [comment]
This would be really useful so we can have differences in design/styles for different platforms, as there are quirks between platforms or we just want to have minor differences in styling without creating additional new component.

This is supported in official stylesheet styling https://reactnative.dev/docs/platform-specific-code#platform-module

**Comment by vadimdemedes** [comment]
```jsx
<View style={{
	...tailwind('flex-1'),
	...Platform.select({
		ios: tailwind('bg-red-500'),
		android: tailwind('bg-blue-500')
	})
}}>
```

**Comment by dorkyboi** [comment]
@vadimdemedes I was looking for something like this because I'm having an issue with dimensions and spacing - they look different in android and ios. You have to agree that `tw('android:py-5 ios:py-10')`would be much more friendly to a developer as there is much less boilerplate code needed.
